<script lang="ts">
	import { page } from "$app/stores";
	import { store } from "@/store.svelte";
	import { notify } from "@/lib/util/notify";
	import Spinner from "@/lib/Spinner.svelte";
	import Error from "@/lib/Error.svelte";
	import axios from "axios";
	import type { PageData } from "./$types";
	import type { MatrixAccountInfo } from "@/types";

	interface MatrixRoom {
		id: string;
		name: string;
		alias?: string;
		topic?: string;
		cycleId?: number;
		cycleName?: string;
		movieTitle?: string;
		joinUrl?: string;
	}

	let { data }: { data: PageData } = $props();
	let config = $derived(store.config);
	let rooms: MatrixRoom[] = $state(data.rooms || []);

	let matrixInfo = $state<MatrixAccountInfo | null>(null);
	let matrixInfoLoading = $state(false);
	let matrixCreateLoading = $state(false);

	async function getMatrixInfo() {
		if (!config?.MOVIE_CLUB?.matrix?.enabled) return;

		matrixInfoLoading = true;
		try {
			const response = await axios.get("/matrix/info");
			matrixInfo = response.data;
		} catch (error) {
			console.error("Failed to get Matrix info:", error);
		} finally {
			matrixInfoLoading = false;
		}
	}

	async function createMatrixAccount() {
		matrixCreateLoading = true;
		try {
			const response = await axios.post("/matrix/create-account");
			if (response.status === 200) {
				notify({
					type: "success",
					text: "Matrix account created successfully",
				});
				getMatrixInfo(); // Refresh info
				// Reload page data to get updated rooms
				window.location.reload();
			}
		} catch (error) {
			console.error("Failed to create Matrix account:", error);
			notify({ type: "error", text: "Failed to create Matrix account" });
		} finally {
			matrixCreateLoading = false;
		}
	}

	function openMatrixRoom(room: MatrixRoom) {
		if (room.joinUrl) {
			window.open(room.joinUrl, "_blank");
		} else if (room.alias && config?.MOVIE_CLUB?.matrix?.serverUrl) {
			// Construct Element/chat client URL
			const serverUrl = config.MOVIE_CLUB.matrix.serverUrl;
			const roomUrl = `${serverUrl}/#/room/${room.alias}`;
			window.open(roomUrl, "_blank");
		}
	}

	// Load Matrix info when component loads
	$effect(() => {
		if (config?.MOVIE_CLUB?.matrix?.enabled) {
			getMatrixInfo();
		}
	});
</script>

<svelte:head>
	<title>Movie Club Community | Watcharr</title>
</svelte:head>

<div class="page">
	<div class="header">
		<h1>Movie Club Community</h1>
		<p>Join community chats for movie club cycles</p>
	</div>

	{#if !config?.MOVIE_CLUB?.matrix?.enabled}
		<div class="info-card">
			<h3>Community Features Not Available</h3>
			<p>
				Matrix chat integration is not currently enabled by the server
				administrator.
			</p>
		</div>
	{:else if matrixInfoLoading}
		<div class="loading">
			<Spinner />
			<span>Loading Matrix account information...</span>
		</div>
	{:else if matrixInfo}
		{#if !matrixInfo.hasMatrixAccount}
			<div class="setup-card">
				<h3>Set Up Your Matrix Account</h3>
				<p>
					To access community chats, you need a Matrix account. You can create
					one automatically or link your existing account in your profile
					settings.
				</p>

				<div class="actions">
					<button
						onclick={createMatrixAccount}
						disabled={matrixCreateLoading}
						class="primary"
					>
						{#if matrixCreateLoading}
							<Spinner />
						{:else}
							Create Matrix Account
						{/if}
					</button>
					<a href="/profile" class="button secondary">Configure in Profile</a>
				</div>
			</div>
		{:else}
			<div class="account-info">
				<h3>Your Matrix Account</h3>
				<div class="account-details">
					<span class="user-id">{matrixInfo.matrixUserId}</span>
					<div class="account-type-info">
						{#if matrixInfo.accountType === "appservice"}
							<span class="account-type as-type"
								>🤖 Application Service Account</span
							>
							<span class="account-desc"
								>Virtual Matrix user managed by Watcharr</span
							>
						{:else if matrixInfo.accountType === "personal"}
							<span class="account-type personal-type">
								👤 {matrixInfo.isAutoGenerated
									? "Personal (Auto-Generated)"
									: "Personal (Custom Linked)"}
							</span>
							<span class="account-desc">
								{matrixInfo.isAutoGenerated
									? "Real Matrix account - access via Element Web"
									: "Your existing Matrix account"}
							</span>
						{:else if matrixInfo.accountType === "legacy"}
							<span class="account-type legacy-type">⚠️ Legacy Account</span>
							<span class="account-desc"
								>Older account format - consider updating in profile</span
							>
						{:else}
							<span class="account-type">
								{matrixInfo.isAutoGenerated
									? "Auto-generated account"
									: "Custom linked account"}
							</span>
						{/if}
					</div>
				</div>
			</div>

			{#if rooms.length > 0}
				<div class="rooms-section">
					<h3>Available Chats</h3>
					<p>
						These are the community chats for cycles you've participated in:
					</p>

					<div class="rooms-grid">
						{#each rooms as room}
							<div class="room-card" onclick={() => openMatrixRoom(room)}>
								<div class="room-header">
									<h4>{room.name}</h4>
									{#if room.cycleName}
										<span class="cycle-name">{room.cycleName}</span>
									{/if}
								</div>

								{#if room.movieTitle}
									<div class="movie-info">
										<span class="movie-title">{room.movieTitle}</span>
									</div>
								{/if}

								{#if room.topic}
									<p class="room-topic">{room.topic}</p>
								{/if}

								<div class="room-footer">
									<button class="join-button">Join Chat</button>
								</div>
							</div>
						{/each}
					</div>
				</div>
			{:else}
				<div class="info-card">
					<h3>No Chats Available</h3>
					<p>
						You don't have access to any community chats yet. Chats are created
						for movie club cycles when they reach the watching phase, and only
						users who participated (nominated or voted) can access them.
					</p>
					<p>
						Participate in movie club cycles to gain access to community chats!
					</p>
					<a href="/movie-club" class="button primary">Go to Movie Club</a>
				</div>
			{/if}
		{/if}
	{/if}
</div>

<style lang="scss">
	.page {
		padding: 30px;
		max-width: 1200px;
		margin: 0 auto;
	}

	.header {
		margin-bottom: 30px;
		text-align: center;

		h1 {
			margin: 0 0 10px 0;
			font-size: 2.5em;
		}

		p {
			margin: 0;
			opacity: 0.8;
			font-size: 1.1em;
		}
	}

	.loading {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 15px;
		padding: 40px;

		span {
			font-size: 1.1em;
		}
	}

	.info-card,
	.setup-card {
		background: var(--card-bg);
		border: 1px solid var(--border-color);
		border-radius: 12px;
		padding: 30px;
		text-align: center;
		margin-bottom: 30px;

		h3 {
			margin: 0 0 15px 0;
			font-size: 1.5em;
		}

		p {
			margin: 0 0 20px 0;
			line-height: 1.6;
			opacity: 0.9;

			&:last-child {
				margin-bottom: 0;
			}
		}
	}

	.setup-card {
		.actions {
			display: flex;
			gap: 15px;
			justify-content: center;
			flex-wrap: wrap;
		}
	}

	.account-info {
		background: var(--card-bg);
		border: 1px solid var(--border-color);
		border-radius: 12px;
		padding: 20px;
		margin-bottom: 30px;

		h3 {
			margin: 0 0 15px 0;
			font-size: 1.3em;
		}

		.account-details {
			display: flex;
			flex-direction: column;
			gap: 10px;

			.user-id {
				font-weight: 500;
				font-family: monospace;
				font-size: 1.1em;
			}

			.account-type-info {
				display: flex;
				flex-direction: column;
				gap: 4px;

				.account-type {
					font-size: 0.95em;
					font-weight: 500;
					display: flex;
					align-items: center;
					gap: 8px;

					&.as-type {
						color: #4a90e2;
					}

					&.personal-type {
						color: #22c55e;
					}

					&.legacy-type {
						color: #f59e0b;
					}
				}

				.account-desc {
					font-size: 0.85em;
					opacity: 0.7;
					line-height: 1.4;
				}
			}
		}
	}

	.rooms-section {
		h3 {
			margin: 0 0 10px 0;
			font-size: 1.5em;
		}

		p {
			margin: 0 0 25px 0;
			opacity: 0.8;
		}
	}

	.rooms-grid {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
		gap: 20px;
	}

	.room-card {
		background: var(--card-bg);
		border: 1px solid var(--border-color);
		border-radius: 12px;
		padding: 20px;
		cursor: pointer;
		transition: all 0.2s ease;

		&:hover {
			border-color: var(--accent-color);
			transform: translateY(-2px);
			box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
		}

		.room-header {
			display: flex;
			justify-content: space-between;
			align-items: flex-start;
			margin-bottom: 10px;

			h4 {
				margin: 0;
				font-size: 1.2em;
				flex: 1;
			}

			.cycle-name {
				background: var(--accent-color);
				color: white;
				padding: 4px 8px;
				border-radius: 6px;
				font-size: 0.8em;
				white-space: nowrap;
				margin-left: 10px;
			}
		}

		.movie-info {
			margin-bottom: 10px;

			.movie-title {
				font-weight: 500;
				color: var(--accent-color);
			}
		}

		.room-topic {
			margin: 0 0 15px 0;
			opacity: 0.8;
			line-height: 1.4;
			font-size: 0.95em;
		}

		.room-footer {
			display: flex;
			justify-content: flex-end;

			.join-button {
				background: var(--accent-color);
				color: white;
				border: none;
				padding: 8px 16px;
				border-radius: 6px;
				font-weight: 500;
				cursor: pointer;
				transition: all 0.2s ease;

				&:hover {
					background: var(--accent-color-dark);
				}
			}
		}
	}

	.button {
		display: inline-flex;
		align-items: center;
		gap: 8px;
		padding: 12px 24px;
		border-radius: 8px;
		text-decoration: none;
		font-weight: 500;
		transition: all 0.2s ease;
		cursor: pointer;
		border: none;
		font-size: 1em;

		&.primary {
			background: var(--accent-color);
			color: white;

			&:hover {
				background: var(--accent-color-dark);
			}
		}

		&.secondary {
			background: transparent;
			color: var(--accent-color);
			border: 1px solid var(--accent-color);

			&:hover {
				background: var(--accent-color);
				color: white;
			}
		}

		&:disabled {
			opacity: 0.6;
			cursor: not-allowed;
		}
	}

	@media (max-width: 768px) {
		.page {
			padding: 20px;
		}

		.rooms-grid {
			grid-template-columns: 1fr;
		}

		.setup-card .actions {
			flex-direction: column;
			align-items: center;
		}
	}
</style>
