package main

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGetOrCreateMatrixUserV2_ASMode(t *testing.T) {
	db := setupTestDB(t)
	
	// Set up test configuration for AS mode
	Config.MOVIE_CLUB.Matrix.AppService.Enabled = true
	
	// Set up global AS manager
	appServiceManager = setupTestASManager(t, db)
	
	user := setupTestUser(t, db, "testuser")

	// Test creating user in AS mode
	matrixUser, err := GetOrCreateMatrixUserV2(db, user.ID, user.Username)
	require.NoError(t, err, "Should create AS user successfully")
	require.NotNil(t, matrixUser, "Matrix user should not be nil")

	assert.Equal(t, AccountTypeAppService, matrixUser.AccountType, "Should create AS account")
	assert.True(t, matrixUser.ASManagedUser, "Should be AS managed")
	assert.True(t, matrixUser.CreatedViaAS, "Should be created via AS")

	// Test getting existing user
	existingUser, err := GetOrCreateMatrixUserV2(db, user.ID, user.Username)
	require.NoError(t, err, "Should get existing user successfully")
	assert.Equal(t, matrixUser.ID, existingUser.ID, "Should return same user")

	// Clean up
	appServiceManager = nil
	Config.MOVIE_CLUB.Matrix.AppService.Enabled = false
}

func TestGetOrCreateMatrixUserV2_PersonalMode(t *testing.T) {
	// Skip this test as it requires Matrix server integration
	t.Skip("Skipping test that requires Matrix server integration")

	db := setupTestDB(t)
	
	// Set up test configuration for personal mode
	Config.MOVIE_CLUB.Matrix.AppService.Enabled = false
	Config.MOVIE_CLUB.Matrix.ServerName = "test.example.com"
	Config.MOVIE_CLUB.Matrix.RegistrationSecret = "test-secret"
	
	// Initialize encryption key
	initializeEncryptionKey()
	
	user := setupTestUser(t, db, "testuser")

	// Test creating user in personal mode
	matrixUser, err := GetOrCreateMatrixUserV2(db, user.ID, user.Username)
	require.NoError(t, err, "Should create personal user successfully")
	require.NotNil(t, matrixUser, "Matrix user should not be nil")

	assert.Equal(t, AccountTypePersonal, matrixUser.AccountType, "Should create personal account")
	assert.False(t, matrixUser.ASManagedUser, "Should not be AS managed")
	assert.False(t, matrixUser.CreatedViaAS, "Should not be created via AS")
	assert.True(t, matrixUser.IsAutoGenerated, "Should be auto generated")
	assert.NotEmpty(t, matrixUser.AccessToken, "Should have access token")
	assert.NotEmpty(t, matrixUser.DeviceID, "Should have device ID")

	// Test getting existing user
	existingUser, err := GetOrCreateMatrixUserV2(db, user.ID, user.Username)
	require.NoError(t, err, "Should get existing user successfully")
	assert.Equal(t, matrixUser.ID, existingUser.ID, "Should return same user")
}

func TestUnlinkMatrixUserV2_ASUser(t *testing.T) {
	db := setupTestDB(t)
	
	// Set up AS manager
	appServiceManager = setupTestASManager(t, db)
	defer func() { appServiceManager = nil }()
	
	user := setupTestUser(t, db, "testuser")

	// Create AS user directly in database
	matrixUser := &MatrixUserV2{
		UserID:          user.ID,
		MatrixUserID:    "@watcharr_123_testuser:test.example.com",
		AccountType:     AccountTypeAppService,
		IsAutoGenerated: true,
		ASManagedUser:   true,
		CreatedViaAS:    true,
		LastSeenAt:      time.Now(),
	}
	
	err := db.Create(matrixUser).Error
	require.NoError(t, err, "Should create test AS user")

	// Test unlinking AS user
	err = UnlinkMatrixUserV2(db, user.ID)
	assert.NoError(t, err, "Should unlink AS user successfully")

	// Verify user is deleted
	var deletedUser MatrixUserV2
	err = db.Where("user_id = ?", user.ID).First(&deletedUser).Error
	assert.Error(t, err, "AS user should be deleted")
}

func TestUnlinkMatrixUserV2_PersonalUser(t *testing.T) {
	db := setupTestDB(t)
	user := setupTestUser(t, db, "testuser")

	// Create personal user directly in database
	matrixUser := &MatrixUserV2{
		UserID:          user.ID,
		MatrixUserID:    "@watcharr_123_testuser:test.example.com",
		AccountType:     AccountTypePersonal,
		IsAutoGenerated: true,
		AccessToken:     "encrypted-token",
		DeviceID:        "test-device",
		ASManagedUser:   false,
		CreatedViaAS:    false,
		LastSeenAt:      time.Now(),
	}
	
	err := db.Create(matrixUser).Error
	require.NoError(t, err, "Should create test personal user")

	// Test unlinking personal user
	err = UnlinkMatrixUserV2(db, user.ID)
	assert.NoError(t, err, "Should unlink personal user successfully")

	// Verify user is soft deleted
	var deletedUser MatrixUserV2
	err = db.Where("user_id = ?", user.ID).First(&deletedUser).Error
	assert.Error(t, err, "Personal user should be soft deleted")

	// Verify user exists with Unscoped
	err = db.Unscoped().Where("user_id = ?", user.ID).First(&deletedUser).Error
	assert.NoError(t, err, "Personal user should exist in soft deleted state")
	assert.NotNil(t, deletedUser.DeletedAt, "Personal user should have deletion timestamp")
}

func TestUnlinkMatrixUserV2_LegacyUser(t *testing.T) {
	db := setupTestDB(t)
	user := setupTestUser(t, db, "testuser")

	// Create legacy user
	legacyUser := &MatrixUser{
		UserID:          user.ID,
		MatrixUserID:    "@watcharr_123_testuser:test.example.com",
		IsAutoGenerated: true,
		AccessToken:     "encrypted-token",
		DeviceID:        "test-device",
	}
	
	err := db.Create(legacyUser).Error
	require.NoError(t, err, "Should create test legacy user")

	// Test unlinking legacy user
	err = UnlinkMatrixUserV2(db, user.ID)
	assert.NoError(t, err, "Should unlink legacy user successfully")

	// Verify user is soft deleted
	var deletedUser MatrixUser
	err = db.Where("user_id = ?", user.ID).First(&deletedUser).Error
	assert.Error(t, err, "Legacy user should be soft deleted")
}

func TestUnlinkMatrixUserV2_NoUser(t *testing.T) {
	db := setupTestDB(t)
	
	// Test unlinking non-existent user
	err := UnlinkMatrixUserV2(db, 999)
	assert.Error(t, err, "Should return error for non-existent user")
	assert.Contains(t, err.Error(), "no Matrix account linked", "Error should mention no account found")
}

func TestMigrateMatrixUsersToV2(t *testing.T) {
	db := setupTestDB(t)
	
	// Initialize encryption for password handling
	initializeEncryptionKey()
	
	// Create test users
	user1 := setupTestUser(t, db, "user1")
	user2 := setupTestUser(t, db, "user2")
	user3 := setupTestUser(t, db, "user3")

	// Create legacy Matrix users
	legacyUsers := []*MatrixUser{
		{
			UserID:              user1.ID,
			MatrixUserID:        "@watcharr_1_user1:test.example.com",
			IsAutoGenerated:     true,
			AccessToken:         "encrypted-token-1",
			DeviceID:            "device-1",
			PasswordExported:    false,
			PasswordExportCount: 0,
		},
		{
			UserID:              user2.ID,
			MatrixUserID:        "@watcharr_2_user2:test.example.com",
			IsAutoGenerated:     false, // Custom account
			AccessToken:         "encrypted-token-2",
			DeviceID:            "device-2",
			PasswordExported:    true,
			PasswordExportCount: 2,
		},
	}

	for _, user := range legacyUsers {
		err := db.Create(user).Error
		require.NoError(t, err, "Should create legacy user")
	}
	
	// Fix user2 to have IsAutoGenerated=false (GORM default overrides it)
	err := db.Model(&MatrixUser{}).Where("user_id = ?", user2.ID).Update("is_auto_generated", false).Error
	require.NoError(t, err, "Should update user2 IsAutoGenerated")
	
	// Verify the data is correctly set
	var stored MatrixUser
	err = db.Where("user_id = ?", user2.ID).First(&stored).Error
	require.NoError(t, err, "Should find user2")
	require.False(t, stored.IsAutoGenerated, "User2 should have IsAutoGenerated=false")

	// Create one V2 user that already exists (should be skipped)
	existingV2User := &MatrixUserV2{
		UserID:          user3.ID,
		MatrixUserID:    "@watcharr_3_user3:test.example.com",
		AccountType:     AccountTypePersonal,
		IsAutoGenerated: true,
		ASManagedUser:   false,
		CreatedViaAS:    false,
		LastSeenAt:      time.Now(),
	}
	err = db.Create(existingV2User).Error
	require.NoError(t, err, "Should create existing V2 user")

	// Run migration
	result, err := MigrateMatrixUsersToV2(db)
	require.NoError(t, err, "Migration should succeed")

	// Verify migration results
	assert.Equal(t, 2, result.TotalLegacyUsers, "Should find 2 legacy users")
	assert.Equal(t, 2, result.MigratedUsers, "Should migrate 2 users")
	assert.Equal(t, 0, result.FailedMigrations, "Should have no failures")
	assert.Equal(t, 0, result.SkippedUsers, "Should have no skipped users")
	assert.Len(t, result.MigratedUserIDs, 2, "Should have 2 migrated user IDs")
	assert.Empty(t, result.Errors, "Should have no errors")

	// Verify V2 users were created
	var v2Users []MatrixUserV2
	err = db.Find(&v2Users).Error
	require.NoError(t, err, "Should find V2 users")
	assert.Len(t, v2Users, 3, "Should have 3 V2 users (2 migrated + 1 existing)")

	// Verify migrated user properties
	for _, v2User := range v2Users {
		if v2User.UserID == user1.ID {
			assert.Equal(t, AccountTypePersonal, v2User.AccountType, "Should be personal account")
			assert.True(t, v2User.IsAutoGenerated, "Should preserve auto generated flag")
			assert.False(t, v2User.ASManagedUser, "Should not be AS managed")
			assert.False(t, v2User.CreatedViaAS, "Should not be created via AS")
			assert.Equal(t, "encrypted-token-1", v2User.AccessToken, "Should preserve access token")
		} else if v2User.UserID == user2.ID {
			assert.Equal(t, AccountTypePersonal, v2User.AccountType, "Should be personal account")
			assert.False(t, v2User.IsAutoGenerated, "Should preserve auto generated flag")
			assert.True(t, v2User.PasswordExported, "Should preserve password exported flag")
			assert.Equal(t, 2, v2User.PasswordExportCount, "Should preserve export count")
		}
	}

	// Verify legacy users are soft deleted
	var legacyCount int64
	err = db.Model(&MatrixUser{}).Count(&legacyCount).Error
	require.NoError(t, err, "Should count legacy users")
	assert.Equal(t, int64(0), legacyCount, "Legacy users should be soft deleted")

	// Verify legacy users exist with Unscoped
	err = db.Unscoped().Model(&MatrixUser{}).Count(&legacyCount).Error
	require.NoError(t, err, "Should count unscoped legacy users")
	assert.Equal(t, int64(2), legacyCount, "Legacy users should exist in soft deleted state")
}

func TestMigrateMatrixUsersToV2_NoLegacyUsers(t *testing.T) {
	db := setupTestDB(t)

	// Run migration with no legacy users
	result, err := MigrateMatrixUsersToV2(db)
	require.NoError(t, err, "Migration should succeed with no users")

	assert.Equal(t, 0, result.TotalLegacyUsers, "Should find 0 legacy users")
	assert.Equal(t, 0, result.MigratedUsers, "Should migrate 0 users")
	assert.Equal(t, 0, result.FailedMigrations, "Should have no failures")
	assert.Equal(t, 0, result.SkippedUsers, "Should have no skipped users")
	assert.Empty(t, result.MigratedUserIDs, "Should have no migrated user IDs")
	assert.Empty(t, result.Errors, "Should have no errors")
}

func TestMigrateSingleMatrixUserToV2(t *testing.T) {
	db := setupTestDB(t)
	initializeEncryptionKey()
	
	user := setupTestUser(t, db, "testuser")

	// Create legacy user
	legacyUser := &MatrixUser{
		UserID:              user.ID,
		MatrixUserID:        "@watcharr_123_testuser:test.example.com",
		IsAutoGenerated:     true,
		AccessToken:         "encrypted-token",
		DeviceID:            "test-device",
		PasswordExported:    false,
		PasswordExportCount: 0,
	}
	
	err := db.Create(legacyUser).Error
	require.NoError(t, err, "Should create legacy user")

	// Test single user migration
	err = MigrateSingleMatrixUserToV2(db, user.ID)
	assert.NoError(t, err, "Single user migration should succeed")

	// Verify V2 user was created
	var v2User MatrixUserV2
	err = db.Where("user_id = ?", user.ID).First(&v2User).Error
	assert.NoError(t, err, "Should find migrated V2 user")

	assert.Equal(t, AccountTypePersonal, v2User.AccountType, "Should be personal account")
	assert.Equal(t, legacyUser.MatrixUserID, v2User.MatrixUserID, "Should preserve Matrix user ID")
	assert.Equal(t, legacyUser.AccessToken, v2User.AccessToken, "Should preserve access token")

	// Verify legacy user is soft deleted
	var deletedLegacyUser MatrixUser
	err = db.Where("user_id = ?", user.ID).First(&deletedLegacyUser).Error
	assert.Error(t, err, "Legacy user should be soft deleted")

	// Test migration of non-existent user
	err = MigrateSingleMatrixUserToV2(db, 999)
	assert.Error(t, err, "Should return error for non-existent user")
	assert.Contains(t, err.Error(), "no legacy Matrix account found", "Error should mention no account found")

	// Create a new user for testing existing V2 account scenario
	user2 := setupTestUser(t, db, "testuser2")
	
	// Create both a legacy account and a V2 account for user2 to simulate the conflict
	legacyUser2 := &MatrixUser{
		UserID:              user2.ID,
		MatrixUserID:        "@watcharr_789_testuser2:test.example.com",
		IsAutoGenerated:     true,
		AccessToken:         "encrypted-token-2",
		DeviceID:            "test-device-2",
		PasswordExported:    false,
		PasswordExportCount: 0,
	}
	err = db.Create(legacyUser2).Error
	require.NoError(t, err, "Should create legacy user for test")
	
	// Create a V2 account for user2 directly to create conflict
	existingV2User2 := &MatrixUserV2{
		UserID:          user2.ID,
		MatrixUserID:    "@watcharr_456_testuser2:test.example.com",
		AccountType:     AccountTypePersonal,
		IsAutoGenerated: true,
		ASManagedUser:   false,
		CreatedViaAS:    false,
		LastSeenAt:      time.Now(),
	}
	err = db.Create(existingV2User2).Error
	require.NoError(t, err, "Should create existing V2 user for test")
	
	// Test migration of user that already has V2 account
	err = MigrateSingleMatrixUserToV2(db, user2.ID)
	assert.Error(t, err, "Should return error for user with existing V2 account")
	assert.Contains(t, err.Error(), "already has a V2 Matrix account", "Error should mention existing V2 account")
}

func TestCreatePersonalMatrixUser(t *testing.T) {
	// Skip this test as it requires Matrix server integration
	t.Skip("Skipping test that requires Matrix server integration")

	db := setupTestDB(t)
	initializeEncryptionKey()
	
	// Set up configuration
	Config.MOVIE_CLUB.Matrix.ServerName = "test.example.com"
	
	user := setupTestUser(t, db, "testuser")

	// Test creating personal user
	matrixUser, err := CreatePersonalMatrixUser(db, user.ID, user.Username)
	require.NoError(t, err, "Should create personal user successfully")
	require.NotNil(t, matrixUser, "Matrix user should not be nil")

	assert.Equal(t, AccountTypePersonal, matrixUser.AccountType, "Should be personal account")
	assert.Equal(t, user.ID, matrixUser.UserID, "User ID should match")
	assert.Contains(t, matrixUser.MatrixUserID, "watcharr_", "Matrix user ID should contain prefix")
	assert.Contains(t, matrixUser.MatrixUserID, user.Username, "Matrix user ID should contain username")
	assert.True(t, matrixUser.IsAutoGenerated, "Should be auto generated")
	assert.False(t, matrixUser.ASManagedUser, "Should not be AS managed")
	assert.False(t, matrixUser.CreatedViaAS, "Should not be created via AS")
	assert.NotEmpty(t, matrixUser.AccessToken, "Should have access token")
	assert.NotEmpty(t, matrixUser.DeviceID, "Should have device ID")

	// Test creating duplicate user
	_, err = CreatePersonalMatrixUser(db, user.ID, user.Username)
	assert.NoError(t, err, "Should return existing user for duplicate creation")

	// Verify user exists in database
	var dbUser MatrixUserV2
	err = db.Where("user_id = ? AND account_type = ?", user.ID, AccountTypePersonal).First(&dbUser).Error
	assert.NoError(t, err, "Personal user should exist in database")
	assert.Equal(t, matrixUser.MatrixUserID, dbUser.MatrixUserID, "Matrix user ID should match")
}