package main

import (
	"bytes"
	"context"
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha1"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"regexp"
	"strings"
	"time"
	"unicode"

	"maunium.net/go/mautrix"
	"maunium.net/go/mautrix/id"
	"gorm.io/gorm"
	"gopkg.in/yaml.v3"
)

// Matrix database models

// MatrixUser stores Matrix user mappings for Watcharr users (legacy model)
type MatrixUser struct {
	GormModel
	UserID              uint       `json:"userId" gorm:"index"`
	MatrixUserID        string     `json:"matrixUserId" gorm:"unique"` // @username:server.name
	IsAutoGenerated     bool       `json:"isAutoGenerated" gorm:"default:true"`
	AccessToken         string     `json:"accessToken"`                // Encrypted access token
	DeviceID            string     `json:"deviceId"`                   // Matrix device ID
	EncryptedPassword   string     `json:"-"`                          // Encrypted password (auto-generated accounts only)
	PasswordExported    bool       `json:"passwordExported" gorm:"default:false"`
	PasswordExportedAt  *time.Time `json:"passwordExportedAt"`
	PasswordExportCount int        `json:"passwordExportCount" gorm:"default:0"`
	User                User       `json:"user,omitempty" gorm:"foreignKey:UserID"`
}

// Matrix account types for hybrid architecture
type MatrixAccountType string

const (
	AccountTypeAppService MatrixAccountType = "appservice"
	AccountTypePersonal   MatrixAccountType = "personal"
)

// MatrixUserV2 stores Matrix user mappings with support for hybrid accounts
type MatrixUserV2 struct {
	GormModel
	UserID              uint              `json:"userId" gorm:"index"`
	MatrixUserID        string            `json:"matrixUserId" gorm:"unique"`     // Full Matrix user ID
	AccountType         MatrixAccountType `json:"accountType"`                    // "appservice" | "personal"
	IsAutoGenerated     bool              `json:"isAutoGenerated"`                // Backward compatibility
	AccessToken         string            `json:"accessToken"`                    // Encrypted token (personal accounts only)
	DeviceID            string            `json:"deviceId"`                       // Matrix device ID (personal accounts only)
	EncryptedPassword   string            `json:"-"`                              // Legacy field, unused for AS
	PasswordExported    bool              `json:"passwordExported"`               // Legacy field
	PasswordExportedAt  *time.Time        `json:"passwordExportedAt"`             // Legacy field
	PasswordExportCount int               `json:"passwordExportCount"`            // Legacy field
	User                User              `json:"user,omitempty" gorm:"foreignKey:UserID"`

	// Application Service specific fields
	ASManagedUser bool      `json:"asManagedUser"` // True for AS virtual users
	CreatedViaAS  bool      `json:"createdViaAS"`  // Whether created via AS
	LastSeenAt    time.Time `json:"lastSeenAt"`    // Last activity timestamp
}

// Matrix room types for better organization
type MatrixRoomType string

const (
	MatrixRoomTypeNews     MatrixRoomType = "news"     // Global news room
	MatrixRoomTypeGeneral  MatrixRoomType = "general"  // Cycle general discussion
	MatrixRoomTypeSpoilers MatrixRoomType = "spoilers" // Cycle spoilers discussion
)

// Matrix space types for hierarchy management
type MatrixSpaceType string

const (
	MatrixSpaceTypeMovieClub MatrixSpaceType = "movie_club" // Main Movie Club space
	MatrixSpaceTypeCycle     MatrixSpaceType = "cycle"      // Individual cycle space
)

// MatrixRoom stores Matrix rooms for movie club cycles
type MatrixRoom struct {
	GormModel
	RoomID      string         `json:"roomId" gorm:"unique"`
	RoomAlias   string         `json:"roomAlias"`
	RoomName    string         `json:"roomName"`      // Explicit room name
	RoomType    MatrixRoomType `json:"roomType"`      // Room type classification
	SpaceID     *string        `json:"spaceId" gorm:"index"` // Parent space
	CycleID     *uint          `json:"cycleId" gorm:"index"` // Optional for News room
	
	// Relationships  
	Space       *MatrixSpace        `json:"space,omitempty" gorm:"foreignKey:SpaceID"`
	Cycle       *MovieClubCycle     `json:"cycle,omitempty" gorm:"foreignKey:CycleID"`
	Members     []MatrixRoomMember  `json:"members,omitempty" gorm:"foreignKey:RoomID"`
}

// MatrixRoomMember tracks room memberships
type MatrixRoomMember struct {
	GormModel
	RoomID     uint       `json:"roomId" gorm:"index"`
	UserID     uint       `json:"userId" gorm:"index"`
	JoinedAt   time.Time  `json:"joinedAt" gorm:"default:CURRENT_TIMESTAMP"`
	Room       MatrixRoom `json:"room,omitempty" gorm:"foreignKey:RoomID"`
	User       User       `json:"user,omitempty" gorm:"foreignKey:UserID"`
}

// MatrixSpace stores the Movie Club space information
type MatrixSpace struct {
	GormModel
	SpaceID       string          `json:"spaceId" gorm:"unique"`
	SpaceName     string          `json:"spaceName"`
	SpaceType     MatrixSpaceType `json:"spaceType"`        // Type classification
	CycleID       *uint           `json:"cycleId" gorm:"index"` // Optional cycle association
	ParentSpaceID *string         `json:"parentSpaceId"`    // Hierarchy support
	
	// Relationships
	Cycle         *MovieClubCycle `json:"cycle,omitempty" gorm:"foreignKey:CycleID"`
	Rooms         []MatrixRoom    `json:"rooms,omitempty" gorm:"foreignKey:SpaceID"`
}

// Matrix token encryption utilities

var encryptionKey []byte

// initializeEncryptionKey generates or retrieves the encryption key for Matrix tokens
func initializeEncryptionKey() error {
	// Use a deterministic key based on Matrix admin token to ensure consistency across restarts
	// This ensures encrypted passwords remain decryptable after server restarts
	keySource := Config.MOVIE_CLUB.Matrix.AdminToken
	if keySource == "" {
		// Fallback to a fixed string if no Matrix config (for development)
		keySource = "watcharr-matrix-encryption-fallback-key-2025"
	}
	
	// Generate 32-byte key from source using SHA-256
	hash := sha256.Sum256([]byte(keySource))
	encryptionKey = hash[:]
	
	return nil
}

// encryptToken encrypts a Matrix access token
func encryptToken(plaintext string) (string, error) {
	if encryptionKey == nil {
		if err := initializeEncryptionKey(); err != nil {
			return "", err
		}
	}

	block, err := aes.NewCipher(encryptionKey)
	if err != nil {
		return "", fmt.Errorf("failed to create cipher: %w", err)
	}

	// Create a GCM cipher mode
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("failed to create GCM: %w", err)
	}

	// Generate nonce
	nonce := make([]byte, gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return "", fmt.Errorf("failed to generate nonce: %w", err)
	}

	// Encrypt the token
	ciphertext := gcm.Seal(nonce, nonce, []byte(plaintext), nil)
	
	// Return base64 encoded encrypted token
	return base64.StdEncoding.EncodeToString(ciphertext), nil
}

// decryptToken decrypts a Matrix access token
func decryptToken(encryptedToken string) (string, error) {
	if encryptionKey == nil {
		return "", errors.New("encryption key not initialized")
	}

	// Decode base64
	ciphertext, err := base64.StdEncoding.DecodeString(encryptedToken)
	if err != nil {
		return "", fmt.Errorf("failed to decode encrypted token: %w", err)
	}

	block, err := aes.NewCipher(encryptionKey)
	if err != nil {
		return "", fmt.Errorf("failed to create cipher: %w", err)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("failed to create GCM: %w", err)
	}

	if len(ciphertext) < gcm.NonceSize() {
		return "", errors.New("ciphertext too short")
	}

	// Extract nonce and encrypted data
	nonce, ciphertext := ciphertext[:gcm.NonceSize()], ciphertext[gcm.NonceSize():]
	
	// Decrypt
	plaintext, err := gcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return "", fmt.Errorf("failed to decrypt token: %w", err)
	}

	return string(plaintext), nil
}

// getDecryptedAccessToken retrieves and decrypts an access token for a Matrix user
func getDecryptedAccessToken(db *gorm.DB, watcharrUserID uint) (string, error) {
	var matrixUser MatrixUser
	if err := db.Where("user_id = ?", watcharrUserID).First(&matrixUser).Error; err != nil {
		return "", fmt.Errorf("failed to find Matrix user: %w", err)
	}

	// Decrypt the access token
	accessToken, err := decryptToken(matrixUser.AccessToken)
	if err != nil {
		return "", fmt.Errorf("failed to decrypt access token: %w", err)
	}

	return accessToken, nil
}

// Matrix error handling utilities

// MatrixError represents a Matrix-specific error with context
type MatrixError struct {
	Operation string
	Err       error
	Context   map[string]interface{}
}

func (e *MatrixError) Error() string {
	return fmt.Sprintf("Matrix %s failed: %v", e.Operation, e.Err)
}

func (e *MatrixError) Unwrap() error {
	return e.Err
}

// newMatrixError creates a new MatrixError with context
func newMatrixError(operation string, err error, context map[string]interface{}) *MatrixError {
	return &MatrixError{
		Operation: operation,
		Err:       err,
		Context:   context,
	}
}

// logAndReturnError logs an error with context and returns a MatrixError
func logAndReturnError(operation string, err error, context map[string]interface{}) error {
	matrixErr := newMatrixError(operation, err, context)
	
	// Log with structured context
	logArgs := []interface{}{"operation", operation, "error", err}
	for k, v := range context {
		logArgs = append(logArgs, k, v)
	}
	slog.Error("Matrix operation failed", logArgs...)
	
	return matrixErr
}

// logAndReturnErrorf logs an error with formatted message and returns a MatrixError
func logAndReturnErrorf(operation string, format string, args ...interface{}) error {
	err := fmt.Errorf(format, args...)
	return logAndReturnError(operation, err, nil)
}

// Matrix input validation utilities

var (
	// Matrix ID patterns
	matrixUserIDRegex  = regexp.MustCompile(`^@[a-z0-9._=-]+:[a-z0-9.-]+\.[a-z]{2,}$`)
	matrixRoomIDRegex  = regexp.MustCompile(`^![a-zA-Z0-9]{18}:[a-z0-9.-]+\.[a-z]{2,}$`)
	matrixAliasRegex   = regexp.MustCompile(`^#[a-z0-9._=-]+:[a-z0-9.-]+\.[a-z]{2,}$`)
	
	// Safe characters for usernames and room names
	safeUsernameRegex = regexp.MustCompile(`^[a-zA-Z0-9._-]+$`)
	safeRoomNameRegex = regexp.MustCompile(`^[a-zA-Z0-9\s._-]+$`)
)

// validateMatrixUserID validates Matrix user ID format
func validateMatrixUserID(userID string) error {
	if userID == "" {
		return errors.New("Matrix user ID cannot be empty")
	}
	
	if len(userID) > 255 {
		return errors.New("Matrix user ID too long")
	}
	
	if !matrixUserIDRegex.MatchString(strings.ToLower(userID)) {
		return errors.New("invalid Matrix user ID format")
	}
	
	return nil
}

// validateAccessToken validates Matrix access token format
func validateAccessToken(token string) error {
	if token == "" {
		return errors.New("access token cannot be empty")
	}
	
	if len(token) < 10 {
		return errors.New("access token too short")
	}
	
	if len(token) > 500 {
		return errors.New("access token too long")
	}
	
	// Check for obviously malicious content
	if strings.Contains(token, "\n") || strings.Contains(token, "\r") {
		return errors.New("access token contains invalid characters")
	}
	
	return nil
}

// sanitizeUsername sanitizes username for Matrix user creation
func sanitizeUsername(username string) (string, error) {
	if username == "" {
		return "", errors.New("username cannot be empty")
	}
	
	// Remove whitespace and convert to lowercase
	username = strings.TrimSpace(strings.ToLower(username))
	
	if len(username) == 0 {
		return "", errors.New("username cannot be empty after sanitization")
	}
	
	if len(username) > 32 {
		return "", errors.New("username too long")
	}
	
	// Replace unsafe characters with underscores
	var sanitized strings.Builder
	for _, r := range username {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '.' || r == '_' || r == '-' {
			sanitized.WriteRune(r)
		} else {
			sanitized.WriteRune('_')
		}
	}
	
	result := sanitized.String()
	
	// Ensure it doesn't start or end with special characters
	result = strings.Trim(result, "._-")
	
	if len(result) == 0 {
		return "", errors.New("username contains no valid characters")
	}
	
	return result, nil
}

// sanitizeRoomName sanitizes room name for Matrix room creation
func sanitizeRoomName(name string) (string, error) {
	if name == "" {
		return "", errors.New("room name cannot be empty")
	}
	
	name = strings.TrimSpace(name)
	
	if len(name) == 0 {
		return "", errors.New("room name cannot be empty after sanitization")
	}
	
	if len(name) > 100 {
		return "", errors.New("room name too long")
	}
	
	// Remove control characters and other dangerous content
	var sanitized strings.Builder
	for _, r := range name {
		if unicode.IsPrint(r) && !unicode.IsControl(r) {
			sanitized.WriteRune(r)
		} else {
			sanitized.WriteRune(' ')
		}
	}
	
	result := strings.TrimSpace(sanitized.String())
	
	// Replace multiple spaces with single spaces
	spaceRegex := regexp.MustCompile(`\s+`)
	result = spaceRegex.ReplaceAllString(result, " ")
	
	return result, nil
}

// validateServerURL validates Matrix server URL format
func validateServerURL(url string) error {
	if url == "" {
		return errors.New("server URL cannot be empty")
	}
	
	if !strings.HasPrefix(url, "https://") && !strings.HasPrefix(url, "http://") {
		return errors.New("server URL must start with http:// or https://")
	}
	
	if len(url) > 255 {
		return errors.New("server URL too long")
	}
	
	// Basic URL safety check
	if strings.Contains(url, " ") || strings.Contains(url, "\n") || strings.Contains(url, "\r") {
		return errors.New("server URL contains invalid characters")
	}
	
	return nil
}

// Shared secret registration structures

// SharedSecretRegistrationRequest represents a request for shared secret user registration
type SharedSecretRegistrationRequest struct {
	Nonce    string `json:"nonce"`
	Username string `json:"username"`
	Password string `json:"password"`
	Admin    bool   `json:"admin"`
	Mac      string `json:"mac"`
}

// SharedSecretRegistrationResponse represents the response from shared secret registration
type SharedSecretRegistrationResponse struct {
	UserID      string `json:"user_id"`
	AccessToken string `json:"access_token"`
	DeviceID    string `json:"device_id"`
}

// SharedSecretNonceResponse represents the response from nonce request
type SharedSecretNonceResponse struct {
	Nonce string `json:"nonce"`
}

// Matrix client management

var matrixClient *mautrix.Client

// InitializeMatrixClient creates and configures the Matrix client
func InitializeMatrixClient() error {
	if !Config.MOVIE_CLUB.Matrix.Enabled {
		slog.Debug("Matrix integration is disabled")
		return nil
	}

	// Initialize encryption key for Matrix tokens
	if err := initializeEncryptionKey(); err != nil {
		return logAndReturnError("encryption_key_init", err, nil)
	}

	settings := Config.MOVIE_CLUB.Matrix
	if settings.ServerURL == "" || settings.AdminToken == "" {
		return logAndReturnError("configuration_validation", 
			errors.New("missing server URL or admin token"), 
			map[string]interface{}{
				"server_url_empty": settings.ServerURL == "",
				"admin_token_empty": settings.AdminToken == "",
			})
	}

	// Validate server URL format
	if err := validateServerURL(settings.ServerURL); err != nil {
		return logAndReturnError("server_url_validation", err, map[string]interface{}{
			"server_url": settings.ServerURL,
		})
	}

	// Create Matrix client
	client, err := mautrix.NewClient(settings.ServerURL, "", "")
	if err != nil {
		return logAndReturnError("client_creation", err, map[string]interface{}{
			"server_url": settings.ServerURL,
		})
	}

	// Set admin access token
	client.AccessToken = settings.AdminToken
	
	matrixClient = client
	
	// Test connection
	if err := testMatrixConnection(); err != nil {
		return logAndReturnError("connection_test", err, map[string]interface{}{
			"server_url": settings.ServerURL,
		})
	}

	slog.Info("Matrix client initialized successfully", 
		"server_url", settings.ServerURL,
		"server_name", settings.ServerName)
	return nil
}

// testMatrixConnection verifies the Matrix connection and admin permissions
func testMatrixConnection() error {
	if matrixClient == nil {
		return logAndReturnError("connection_test", 
			errors.New("matrix client not initialized"), nil)
	}

	// Test with a simple whoami request
	resp, err := matrixClient.Whoami(context.Background())
	if err != nil {
		return logAndReturnError("authentication_test", err, map[string]interface{}{
			"server_url": Config.MOVIE_CLUB.Matrix.ServerURL,
		})
	}

	slog.Debug("Matrix connection test successful", "user_id", resp.UserID)
	return nil
}

// User management functions

// GetOrCreateMatrixUserV2 creates a new Matrix user using the hybrid system (AS or personal account)
func GetOrCreateMatrixUserV2(db *gorm.DB, watcharrUserID uint, username string) (*MatrixUserV2, error) {
	// Check if user already has a Matrix account
	var existingUser MatrixUserV2
	if err := db.Where("user_id = ?", watcharrUserID).First(&existingUser).Error; err == nil {
		return &existingUser, nil
	}

	// Determine account type based on configuration
	if Config.MOVIE_CLUB.Matrix.AppService.Enabled && appServiceManager != nil {
		// Create AS user
		return appServiceManager.CreateUser(watcharrUserID, username)
	} else {
		// Create personal account using shared secret registration
		return CreatePersonalMatrixUser(db, watcharrUserID, username)
	}
}

// CreatePersonalMatrixUser creates a personal Matrix user account via manual linking only
// Note: Automatic personal account creation via shared secret has been removed for simplicity
func CreatePersonalMatrixUser(db *gorm.DB, watcharrUserID uint, username string) (*MatrixUserV2, error) {
	errContext := map[string]interface{}{
		"watcharr_user_id": watcharrUserID,
		"username": username,
		"account_type": "personal",
	}

	// Check for existing personal account
	var existingUser MatrixUserV2
	if err := db.Where("user_id = ? AND account_type = ?", watcharrUserID, AccountTypePersonal).First(&existingUser).Error; err == nil {
		return &existingUser, nil
	}

	// Personal accounts can only be created via manual linking now
	return nil, logAndReturnError("personal_account_creation", 
		errors.New("personal Matrix accounts can only be created via manual linking - use Application Service accounts for automatic creation"), 
		errContext)
}

// GetOrCreateMatrixUser is a legacy wrapper that creates MatrixUser (old system)
func GetOrCreateMatrixUser(db *gorm.DB, watcharrUserID uint, username string) (*MatrixUser, error) {
	// Check if user already has a legacy Matrix account
	var existingUser MatrixUser
	if err := db.Where("user_id = ?", watcharrUserID).First(&existingUser).Error; err == nil {
		return &existingUser, nil
	}

	// Create new legacy user
	return CreateMatrixUser(db, watcharrUserID, username)
}

// CreateMatrixUser creates a new Matrix user for a Watcharr user (legacy function)
func CreateMatrixUser(db *gorm.DB, watcharrUserID uint, username string) (*MatrixUser, error) {
	errContext := map[string]interface{}{
		"watcharr_user_id": watcharrUserID,
		"username": username,
	}

	if matrixClient == nil {
		return nil, logAndReturnError("user_creation", 
			errors.New("matrix client not initialized"), errContext)
	}

	// Check if there's a soft-deleted auto-generated account for this user that can be reactivated
	var existingMatrixUser MatrixUser
	if err := db.Unscoped().Where("user_id = ? AND is_auto_generated = true", watcharrUserID).First(&existingMatrixUser).Error; err == nil {
		// Found a soft-deleted auto-generated account - reactivate it with a new Matrix account
		if existingMatrixUser.DeletedAt.Valid {
			slog.Info("Found soft-deleted auto-generated Matrix account - will reactivate",
				"watcharr_user_id", watcharrUserID,
				"old_matrix_user_id", existingMatrixUser.MatrixUserID,
				"deleted_at", existingMatrixUser.DeletedAt.Time)
		}
	}

	// Sanitize username for Matrix compatibility
	sanitizedUsername, err := sanitizeUsername(username)
	if err != nil {
		return nil, logAndReturnError("username_sanitization", err, errContext)
	}
	errContext["sanitized_username"] = sanitizedUsername

	// Generate Matrix user localpart (username without @server.name)
	localpart := fmt.Sprintf("watcharr_%d_%s", watcharrUserID, sanitizedUsername)
	
	// Generate Matrix user ID
	serverName := Config.MOVIE_CLUB.Matrix.ServerName
	matrixUserID := fmt.Sprintf("@%s:%s", localpart, serverName)
	errContext["matrix_user_id"] = matrixUserID

	// Generate random password for the user
	password, err := generateRandomPassword()
	if err != nil {
		return nil, logAndReturnError("password_generation", err, errContext)
	}

	// Note: Shared secret registration has been removed for simplicity
	// This legacy function now only supports placeholder mode
	if false { // Disable shared secret registration permanently
		// Use shared secret registration
		slog.Info("Creating Matrix user via shared secret registration", 
			"watcharr_user_id", watcharrUserID,
			"matrix_user_id", matrixUserID)
		
		var wasReactivated bool
		registrationResponse, err := RegisterUserWithSharedSecret(localpart, password, false)
		if err != nil {
			// Check if the error is due to user already existing
			if strings.Contains(err.Error(), "User ID already taken") || 
			   strings.Contains(err.Error(), "user already exists") ||
			   strings.Contains(err.Error(), "M_USER_IN_USE") {
				
				// If we have a soft-deleted record for this user, this is a reactivation
				if existingMatrixUser.ID != 0 && existingMatrixUser.DeletedAt.Valid {
					slog.Info("Matrix user exists and we have soft-deleted record - attempting reactivation", 
						"watcharr_user_id", watcharrUserID, 
						"matrix_user_id", matrixUserID)
					
					// Attempt to reactivate the Matrix account on the Matrix server
					reactivatedResponse, err := ReactivateMatrixAccount(matrixUserID, password)
					if err != nil {
						return nil, logAndReturnError("matrix_reactivation_failed", fmt.Errorf(
							"failed to reactivate Matrix account on server: %w", err), errContext)
					}
					
					registrationResponse = reactivatedResponse
					wasReactivated = true
					slog.Info("Successfully reactivated Matrix account on server", 
						"watcharr_user_id", watcharrUserID, 
						"matrix_user_id", registrationResponse.UserID)
				} else {
					// User exists but we don't have a record - this shouldn't happen for auto-generated accounts
					return nil, logAndReturnError("user_exists_no_record", fmt.Errorf(
						"Matrix user %s already exists but no Watcharr record found for reactivation", matrixUserID), errContext)
				}
			} else {
				return nil, logAndReturnError("shared_secret_registration", err, errContext)
			}
		}
		
		// Encrypt the real access token before storing
		encryptedToken, err := encryptToken(registrationResponse.AccessToken)
		if err != nil {
			return nil, logAndReturnError("token_encryption", err, errContext)
		}

		// Encrypt the password for credential export feature
		encryptedPassword, err := encryptToken(password)
		if err != nil {
			return nil, logAndReturnError("password_encryption", err, errContext)
		}

		// Store in database - either create new or update existing (reactivation)
		var matrixUser *MatrixUser
		if existingMatrixUser.ID != 0 && existingMatrixUser.DeletedAt.Valid {
			// Reactivating existing soft-deleted record
			matrixUser = &existingMatrixUser
			matrixUser.MatrixUserID = registrationResponse.UserID  // Use the new Matrix user ID
			matrixUser.AccessToken = encryptedToken
			matrixUser.DeviceID = registrationResponse.DeviceID
			matrixUser.EncryptedPassword = encryptedPassword
			matrixUser.DeletedAt = gorm.DeletedAt{} // Undelete the record
			// Reset password export flags since user will need to export credentials again
			matrixUser.PasswordExported = false
			matrixUser.PasswordExportedAt = nil
			matrixUser.PasswordExportCount = 0
			
			// Update the existing record
			if err := db.Unscoped().Save(matrixUser).Error; err != nil {
				return nil, logAndReturnError("database_reactivate", err, errContext)
			}
			
			slog.Info("Reactivated existing Matrix user database record",
				"watcharr_user_id", watcharrUserID,
				"old_matrix_user_id", existingMatrixUser.MatrixUserID,
				"new_matrix_user_id", registrationResponse.UserID)
		} else {
			// Creating new record
			matrixUser = &MatrixUser{
				UserID:            watcharrUserID,
				MatrixUserID:      registrationResponse.UserID,
				IsAutoGenerated:   true,
				AccessToken:       encryptedToken,
				DeviceID:          registrationResponse.DeviceID,
				EncryptedPassword: encryptedPassword,
			}

			if err := db.Create(matrixUser).Error; err != nil {
				return nil, logAndReturnError("database_create", err, errContext)
			}
		}

		// Log appropriate message based on whether this was creation or reactivation
		if wasReactivated {
			if existingMatrixUser.ID != 0 && existingMatrixUser.DeletedAt.Valid {
				slog.Info("Reactivated Matrix account by creating new variant and updating database record", 
					"watcharr_user_id", watcharrUserID, 
					"new_matrix_user_id", registrationResponse.UserID)
			} else {
				slog.Info("Created new Matrix account variant due to username conflict", 
					"watcharr_user_id", watcharrUserID, 
					"new_matrix_user_id", registrationResponse.UserID)
			}
		} else {
			slog.Info("Created Matrix user via shared secret", 
				"watcharr_user_id", watcharrUserID, 
				"matrix_user_id", registrationResponse.UserID)
		}
		return matrixUser, nil
	} else {
		// Fall back to placeholder implementation
		slog.Warn("Shared secret not configured - using placeholder Matrix user creation", 
			"matrix_user_id", matrixUserID,
			"note", "Configure registrationSecret in Matrix settings for real user creation")

		// Create a dummy access token for now - in production this would come from actual Matrix login
		accessToken := "placeholder_token_" + hex.EncodeToString([]byte(matrixUserID))
		
		// Encrypt the access token before storing
		encryptedToken, err := encryptToken(accessToken)
		if err != nil {
			return nil, logAndReturnError("token_encryption", err, errContext)
		}

		// Store in database (placeholder - no real password available)
		matrixUser := &MatrixUser{
			UserID:            watcharrUserID,
			MatrixUserID:      matrixUserID,
			IsAutoGenerated:   true,
			AccessToken:       encryptedToken,
			DeviceID:          "placeholder_device",
			EncryptedPassword: "", // No password for placeholder users
		}

		if err := db.Create(matrixUser).Error; err != nil {
			return nil, logAndReturnError("database_create", err, errContext)
		}

		slog.Info("Created placeholder Matrix user", "watcharr_user_id", watcharrUserID, "matrix_user_id", matrixUserID)
		return matrixUser, nil
	}
}

// LinkCustomMatrixUser validates and links a custom Matrix user
func LinkCustomMatrixUser(db *gorm.DB, watcharrUserID uint, matrixUserID string, accessToken string) error {
	errContext := map[string]interface{}{
		"watcharr_user_id": watcharrUserID,
		"matrix_user_id": matrixUserID,
	}

	// Validate Matrix user ID format
	if err := validateMatrixUserID(matrixUserID); err != nil {
		return logAndReturnError("user_id_validation", err, errContext)
	}

	// Validate access token format
	if err := validateAccessToken(accessToken); err != nil {
		return logAndReturnError("access_token_validation", err, errContext)
	}

	// Validate Matrix user exists and token works
	if err := ValidateMatrixUser(matrixUserID, accessToken); err != nil {
		return logAndReturnError("user_validation", err, errContext)
	}

	// Check for existing Matrix users for this Watcharr user
	var existingUsers []MatrixUser
	if err := db.Where("user_id = ?", watcharrUserID).Find(&existingUsers).Error; err != nil {
		slog.Warn("Failed to check existing Matrix users", 
			"watcharr_user_id", watcharrUserID, 
			"error", err)
	} else {
		slog.Info("Found existing Matrix users before linking", 
			"watcharr_user_id", watcharrUserID, 
			"count", len(existingUsers))
		for i, user := range existingUsers {
			slog.Info("Existing Matrix user", 
				"index", i,
				"matrix_user_id", user.MatrixUserID,
				"is_auto_generated", user.IsAutoGenerated)
		}
	}

	// Get user's current Matrix rooms before removing auto-generated account
	var previousRooms []MatrixRoom
	if len(existingUsers) > 0 {
		rooms, err := GetUserCurrentMatrixRooms(db, watcharrUserID)
		if err != nil {
			slog.Warn("Failed to get user's current rooms for transfer", 
				"watcharr_user_id", watcharrUserID, 
				"error", err)
		} else {
			previousRooms = rooms
			slog.Info("Found rooms for account transfer", 
				"watcharr_user_id", watcharrUserID, 
				"room_count", len(previousRooms))
		}
	}

	// Remove auto-generated user if exists
	if err := RemoveAutoGeneratedUser(db, watcharrUserID); err != nil {
		slog.Warn("Failed to remove auto-generated user", 
			"watcharr_user_id", watcharrUserID, 
			"error", err)
	}

	// Encrypt the access token before storing
	encryptedToken, err := encryptToken(accessToken)
	if err != nil {
		return logAndReturnError("token_encryption", err, errContext)
	}

	// Store custom user mapping
	matrixUser := &MatrixUser{
		UserID:          watcharrUserID,
		MatrixUserID:    matrixUserID,
		IsAutoGenerated: false,
		AccessToken:     encryptedToken,
	}

	slog.Info("Creating Matrix user record", 
		"watcharr_user_id", watcharrUserID,
		"matrix_user_id", matrixUserID,
		"is_auto_generated", matrixUser.IsAutoGenerated)

	// Create the record and then explicitly update the IsAutoGenerated field
	// This works around GORM default value behavior
	if err := db.Create(matrixUser).Error; err != nil {
		return logAndReturnError("database_create", err, errContext)
	}

	// Explicitly update the IsAutoGenerated field to ensure it's set correctly
	if err := db.Model(matrixUser).Update("is_auto_generated", false).Error; err != nil {
		slog.Warn("Failed to update is_auto_generated flag", 
			"watcharr_user_id", watcharrUserID,
			"error", err)
	}

	// Verify what was actually created
	var createdUser MatrixUser
	if err := db.Where("user_id = ? AND matrix_user_id = ?", watcharrUserID, matrixUserID).First(&createdUser).Error; err != nil {
		slog.Warn("Failed to verify created Matrix user", "error", err)
	} else {
		slog.Info("Verified created Matrix user", 
			"watcharr_user_id", createdUser.UserID,
			"matrix_user_id", createdUser.MatrixUserID,
			"is_auto_generated", createdUser.IsAutoGenerated)
	}

	// Invite the new custom account to previously accessible rooms
	if len(previousRooms) > 0 {
		slog.Info("Inviting custom Matrix account to previous rooms", 
			"watcharr_user_id", watcharrUserID,
			"matrix_user_id", matrixUserID,
			"room_count", len(previousRooms))
		
		if err := InviteUserToExistingRooms(db, matrixUserID, watcharrUserID, previousRooms); err != nil {
			slog.Warn("Failed to invite custom Matrix user to some previous rooms", 
				"watcharr_user_id", watcharrUserID,
				"matrix_user_id", matrixUserID,
				"error", err,
				"note", "User may need to be manually invited to some rooms")
		}
	}

	slog.Info("Linked custom Matrix user", "watcharr_user_id", watcharrUserID, "matrix_user_id", matrixUserID)
	return nil
}

// UnlinkMatrixUser removes a user's Matrix account link
// UnlinkMatrixUserV2 handles unlinking for both legacy and new account types
func UnlinkMatrixUserV2(db *gorm.DB, watcharrUserID uint) error {
	errContext := map[string]interface{}{
		"watcharr_user_id": watcharrUserID,
	}

	// Check for new account type first
	var matrixUserV2 MatrixUserV2
	if err := db.Where("user_id = ?", watcharrUserID).First(&matrixUserV2).Error; err == nil {
		// Handle new account type
		return unlinkMatrixUserV2(db, &matrixUserV2, watcharrUserID, errContext)
	}

	// Check for legacy account
	var matrixUser MatrixUser
	if err := db.Where("user_id = ?", watcharrUserID).First(&matrixUser).Error; err == nil {
		// Handle legacy account
		return unlinkLegacyMatrixUser(db, &matrixUser, watcharrUserID, errContext)
	}

	return fmt.Errorf("no Matrix account linked for this user")
}

// unlinkMatrixUserV2 handles unlinking for new MatrixUserV2 accounts
func unlinkMatrixUserV2(db *gorm.DB, matrixUser *MatrixUserV2, watcharrUserID uint, errContext map[string]interface{}) error {
	errContext["matrix_user_id"] = matrixUser.MatrixUserID
	errContext["account_type"] = matrixUser.AccountType
	errContext["is_auto_generated"] = matrixUser.IsAutoGenerated
	errContext["as_managed_user"] = matrixUser.ASManagedUser

	if matrixUser.AccountType == AccountTypeAppService {
		// For AS users, use the Application Service manager to delete them
		if appServiceManager != nil {
			slog.Info("Deleting Application Service user",
				"watcharr_user_id", watcharrUserID,
				"matrix_user_id", matrixUser.MatrixUserID)
			
			if err := appServiceManager.DeleteUser(watcharrUserID); err != nil {
				return logAndReturnError("as_user_deletion", err, errContext)
			}
		} else {
			// If AS manager not available, just remove from database
			slog.Warn("Application Service manager not available, removing user from database only",
				"watcharr_user_id", watcharrUserID,
				"matrix_user_id", matrixUser.MatrixUserID)
			
			if err := db.Delete(matrixUser).Error; err != nil {
				return logAndReturnError("database_delete", err, errContext)
			}
		}
	} else if matrixUser.AccountType == AccountTypePersonal {
		// For personal accounts, use similar logic to legacy accounts
		if matrixUser.IsAutoGenerated {
			// Auto-generated personal accounts: deactivate on server
			slog.Info("Removing auto-generated personal Matrix user from rooms and deactivating",
				"watcharr_user_id", watcharrUserID,
				"matrix_user_id", matrixUser.MatrixUserID)
			
			if err := RemoveUserFromMatrixRooms(db, matrixUser.MatrixUserID, watcharrUserID); err != nil {
				slog.Warn("Failed to remove Matrix user from some rooms", "error", err)
			}
			
			if err := DeactivateMatrixUser(db, matrixUser.MatrixUserID); err != nil {
				slog.Warn("Failed to deactivate Matrix user on server", "error", err)
			}
			
			// Soft delete the account for potential reactivation
			if err := db.Delete(matrixUser).Error; err != nil {
				return logAndReturnError("database_delete", err, errContext)
			}
		} else {
			// Custom personal accounts: preserve on server
			slog.Info("Unlinking custom personal Matrix account - preserving user on Matrix server",
				"watcharr_user_id", watcharrUserID,
				"matrix_user_id", matrixUser.MatrixUserID)
			
			if err := db.Delete(matrixUser).Error; err != nil {
				return logAndReturnError("database_delete", err, errContext)
			}
		}
	}

	slog.Info("Successfully unlinked Matrix user",
		"watcharr_user_id", watcharrUserID,
		"matrix_user_id", matrixUser.MatrixUserID,
		"account_type", matrixUser.AccountType)

	return nil
}

// unlinkLegacyMatrixUser handles unlinking for legacy MatrixUser accounts
func unlinkLegacyMatrixUser(db *gorm.DB, matrixUser *MatrixUser, watcharrUserID uint, errContext map[string]interface{}) error {
	errContext["matrix_user_id"] = matrixUser.MatrixUserID
	errContext["is_auto_generated"] = matrixUser.IsAutoGenerated

	// Handle different unlinking behavior based on account type
	if matrixUser.IsAutoGenerated {
		// For auto-generated accounts, remove from rooms and deactivate the user on Matrix server
		slog.Info("Removing auto-generated Matrix user from all rooms before deactivation",
			"watcharr_user_id", watcharrUserID,
			"matrix_user_id", matrixUser.MatrixUserID)
		
		if err := RemoveUserFromMatrixRooms(db, matrixUser.MatrixUserID, watcharrUserID); err != nil {
			slog.Warn("Failed to remove Matrix user from some rooms",
				"watcharr_user_id", watcharrUserID,
				"matrix_user_id", matrixUser.MatrixUserID,
				"error", err,
				"note", "User may remain in some rooms on Matrix server")
		}
		
		slog.Info("Attempting to deactivate auto-generated Matrix user on server",
			"watcharr_user_id", watcharrUserID,
			"matrix_user_id", matrixUser.MatrixUserID)
		
		if err := DeactivateMatrixUser(db, matrixUser.MatrixUserID); err != nil {
			// Log the error but don't fail the unlinking process
			slog.Warn("Failed to deactivate Matrix user on server",
				"watcharr_user_id", watcharrUserID,
				"matrix_user_id", matrixUser.MatrixUserID,
				"error", err,
				"note", "User will be removed from Watcharr database but may remain active on Matrix server")
		}
		
		// Soft delete the account for potential reactivation
		if err := db.Delete(matrixUser).Error; err != nil {
			return logAndReturnError("database_delete", err, errContext)
		}
	} else {
		// For custom accounts, we only remove from Watcharr - preserve the Matrix account
		// The user can manually leave rooms if they wish
		slog.Info("Unlinking custom Matrix account - preserving user on Matrix server",
			"watcharr_user_id", watcharrUserID,
			"matrix_user_id", matrixUser.MatrixUserID)
		
		if err := db.Delete(matrixUser).Error; err != nil {
			return logAndReturnError("database_delete", err, errContext)
		}
	}

	slog.Info("Successfully unlinked legacy Matrix user",
		"watcharr_user_id", watcharrUserID,
		"matrix_user_id", matrixUser.MatrixUserID)

	return nil
}

// Legacy function - updated to use new hybrid system
func UnlinkMatrixUser(db *gorm.DB, watcharrUserID uint) error {
	return UnlinkMatrixUserV2(db, watcharrUserID)
}

// Migration functions for existing Matrix users

// MigrateMatrixUsersToV2 migrates all legacy MatrixUser accounts to MatrixUserV2
func MigrateMatrixUsersToV2(db *gorm.DB) (*MatrixMigrationResult, error) {
	result := &MatrixMigrationResult{
		TotalLegacyUsers:    0,
		MigratedUsers:       0,
		FailedMigrations:    0,
		SkippedUsers:        0,
		MigratedUserIDs:     make([]uint, 0),
		Errors:              make([]string, 0),
	}

	// Get all legacy Matrix users
	var legacyUsers []MatrixUser
	if err := db.Find(&legacyUsers).Error; err != nil {
		return result, fmt.Errorf("failed to fetch legacy Matrix users: %w", err)
	}

	result.TotalLegacyUsers = len(legacyUsers)
	
	if len(legacyUsers) == 0 {
		slog.Info("No legacy Matrix users found for migration")
		return result, nil
	}

	slog.Info("Starting Matrix user migration", "total_users", len(legacyUsers))

	for _, legacyUser := range legacyUsers {
		// Check if user already has a V2 account
		var existingV2User MatrixUserV2
		if err := db.Where("user_id = ?", legacyUser.UserID).First(&existingV2User).Error; err == nil {
			slog.Info("User already has V2 account, skipping migration",
				"watcharr_user_id", legacyUser.UserID,
				"legacy_matrix_user_id", legacyUser.MatrixUserID,
				"v2_matrix_user_id", existingV2User.MatrixUserID)
			result.SkippedUsers++
			continue
		}

		// Migrate the user
		if err := migrateSingleUserToV2(db, &legacyUser); err != nil {
			errorMsg := fmt.Sprintf("Failed to migrate user %d (%s): %v", 
				legacyUser.UserID, legacyUser.MatrixUserID, err)
			slog.Error("Matrix user migration failed",
				"watcharr_user_id", legacyUser.UserID,
				"matrix_user_id", legacyUser.MatrixUserID,
				"error", err)
			
			result.FailedMigrations++
			result.Errors = append(result.Errors, errorMsg)
			continue
		}

		result.MigratedUsers++
		result.MigratedUserIDs = append(result.MigratedUserIDs, legacyUser.UserID)
		
		slog.Info("Successfully migrated Matrix user",
			"watcharr_user_id", legacyUser.UserID,
			"matrix_user_id", legacyUser.MatrixUserID)
	}

	slog.Info("Matrix user migration completed",
		"total_users", result.TotalLegacyUsers,
		"migrated", result.MigratedUsers,
		"skipped", result.SkippedUsers,
		"failed", result.FailedMigrations)

	return result, nil
}

// migrateSingleUserToV2 migrates a single legacy MatrixUser to MatrixUserV2
func migrateSingleUserToV2(db *gorm.DB, legacyUser *MatrixUser) error {
	// Create new V2 user with legacy data
	v2User := &MatrixUserV2{
		UserID:              legacyUser.UserID,
		MatrixUserID:        legacyUser.MatrixUserID,
		AccountType:         AccountTypePersonal, // Legacy accounts are personal accounts
		IsAutoGenerated:     legacyUser.IsAutoGenerated,
		AccessToken:         legacyUser.AccessToken,
		DeviceID:            legacyUser.DeviceID,
		EncryptedPassword:   legacyUser.EncryptedPassword,
		PasswordExported:    legacyUser.PasswordExported,
		PasswordExportedAt:  legacyUser.PasswordExportedAt,
		PasswordExportCount: legacyUser.PasswordExportCount,
		ASManagedUser:       false, // Legacy accounts are not AS managed
		CreatedViaAS:        false, // Legacy accounts were not created via AS
		LastSeenAt:          time.Now(), // Set current time as last seen
	}

	// Start transaction for atomic migration
	return db.Transaction(func(tx *gorm.DB) error {
		// Create the V2 user
		if err := tx.Create(v2User).Error; err != nil {
			return fmt.Errorf("failed to create V2 user: %w", err)
		}

		// Mark legacy user as migrated (soft delete)
		if err := tx.Delete(legacyUser).Error; err != nil {
			return fmt.Errorf("failed to soft delete legacy user: %w", err)
		}

		return nil
	})
}

// MatrixMigrationResult represents the result of migrating Matrix users
type MatrixMigrationResult struct {
	TotalLegacyUsers    int      `json:"totalLegacyUsers"`
	MigratedUsers       int      `json:"migratedUsers"`
	FailedMigrations    int      `json:"failedMigrations"`
	SkippedUsers        int      `json:"skippedUsers"`
	MigratedUserIDs     []uint   `json:"migratedUserIds"`
	Errors              []string `json:"errors"`
}

// MigrateSingleMatrixUserToV2 migrates a specific user's Matrix account to V2
func MigrateSingleMatrixUserToV2(db *gorm.DB, watcharrUserID uint) error {
	var legacyUser MatrixUser
	if err := db.Where("user_id = ?", watcharrUserID).First(&legacyUser).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return fmt.Errorf("no legacy Matrix account found for user %d", watcharrUserID)
		}
		return fmt.Errorf("failed to find legacy Matrix user: %w", err)
	}

	// Check if user already has V2 account
	var existingV2User MatrixUserV2
	if err := db.Where("user_id = ?", watcharrUserID).First(&existingV2User).Error; err == nil {
		return fmt.Errorf("user %d already has a V2 Matrix account", watcharrUserID)
	}

	return migrateSingleUserToV2(db, &legacyUser)
}


// RemoveAutoGeneratedUser removes an auto-generated Matrix user
func RemoveAutoGeneratedUser(db *gorm.DB, watcharrUserID uint) error {
	errContext := map[string]interface{}{
		"watcharr_user_id": watcharrUserID,
	}

	var matrixUser MatrixUser
	if err := db.Where("user_id = ? AND is_auto_generated = true", watcharrUserID).First(&matrixUser).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil // No auto-generated user to remove
		}
		return logAndReturnError("database_find", err, errContext)
	}

	errContext["matrix_user_id"] = matrixUser.MatrixUserID

	// Remove user from all Matrix rooms before deactivation
	slog.Info("Removing auto-generated Matrix user from all rooms",
		"watcharr_user_id", watcharrUserID,
		"matrix_user_id", matrixUser.MatrixUserID)
	
	if err := RemoveUserFromMatrixRooms(db, matrixUser.MatrixUserID, watcharrUserID); err != nil {
		slog.Warn("Failed to remove Matrix user from some rooms",
			"watcharr_user_id", watcharrUserID,
			"matrix_user_id", matrixUser.MatrixUserID,
			"error", err,
			"note", "User may remain in some rooms on Matrix server")
	}

	// Attempt to deactivate user on Matrix server
	slog.Info("Attempting to deactivate auto-generated Matrix user on server",
		"watcharr_user_id", watcharrUserID,
		"matrix_user_id", matrixUser.MatrixUserID)
	
	if err := DeactivateMatrixUser(db, matrixUser.MatrixUserID); err != nil {
		// Log the error but don't fail the removal process
		slog.Warn("Failed to deactivate Matrix user on server",
			"watcharr_user_id", watcharrUserID,
			"matrix_user_id", matrixUser.MatrixUserID,
			"error", err,
			"note", "User will be removed from Watcharr database but may remain active on Matrix server")
	}

	// Remove from our database (hard delete)
	if err := db.Unscoped().Delete(&matrixUser).Error; err != nil {
		return logAndReturnError("database_delete", err, errContext)
	}

	slog.Info("Removed auto-generated Matrix user", "watcharr_user_id", watcharrUserID, "matrix_user_id", matrixUser.MatrixUserID)
	return nil
}

// ValidateMatrixUser checks if a Matrix user exists and token is valid
func ValidateMatrixUser(matrixUserID, accessToken string) error {
	errContext := map[string]interface{}{
		"matrix_user_id": matrixUserID,
		"server_url": Config.MOVIE_CLUB.Matrix.ServerURL,
	}

	// Create temporary client with user's token
	tempClient, err := mautrix.NewClient(Config.MOVIE_CLUB.Matrix.ServerURL, id.UserID(matrixUserID), "")
	if err != nil {
		return logAndReturnError("client_creation", err, errContext)
	}

	tempClient.AccessToken = accessToken

	// Test with whoami
	resp, err := tempClient.Whoami(context.Background())
	if err != nil {
		return logAndReturnError("user_validation", err, errContext)
	}

	if resp.UserID.String() != matrixUserID {
		return logAndReturnError("user_id_mismatch", 
			errors.New("user ID mismatch"), 
			map[string]interface{}{
				"expected": matrixUserID,
				"actual": resp.UserID.String(),
			})
	}

	return nil
}


// Utility functions

// generateRandomPassword creates a random password for Matrix users
func generateRandomPassword() (string, error) {
	bytes := make([]byte, 16)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}

// Matrix URL utilities

// getMatrixServerURL returns the Matrix server URL with trailing slash removed
func getMatrixServerURL() string {
	return strings.TrimSuffix(Config.MOVIE_CLUB.Matrix.ServerURL, "/")
}

// Matrix server detection and compatibility functions

// MatrixServerInfo holds information about a Matrix server
type MatrixServerInfo struct {
	ServerType   MatrixServerType `json:"serverType"`
	ServerName   string           `json:"serverName"`
	Version      string           `json:"version"`
	Capabilities []string         `json:"capabilities"`
}

// DetectMatrixServerType attempts to detect the Matrix server type
func DetectMatrixServerType(serverURL string) (MatrixServerType, error) {
	// Try to get server information from /_matrix/client/versions endpoint
	versionsURL := fmt.Sprintf("%s/_matrix/client/versions", strings.TrimSuffix(serverURL, "/"))
	
	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Get(versionsURL)
	if err != nil {
		return MatrixServerTypeAuto, fmt.Errorf("failed to connect to Matrix server: %w", err)
	}
	defer resp.Body.Close()
	
	if resp.StatusCode != http.StatusOK {
		return MatrixServerTypeAuto, fmt.Errorf("server returned status %d", resp.StatusCode)
	}
	
	var versionsResp struct {
		Versions []string `json:"versions"`
		Server   struct {
			Name    string `json:"name"`
			Version string `json:"version"`
		} `json:"unstable_features,omitempty"`
	}
	
	if err := json.NewDecoder(resp.Body).Decode(&versionsResp); err != nil {
		return MatrixServerTypeAuto, fmt.Errorf("failed to parse versions response: %w", err)
	}
	
	// Try to get server info from /_synapse/admin/v1/server_version endpoint (Synapse specific)
	synapseURL := fmt.Sprintf("%s/_synapse/admin/v1/server_version", strings.TrimSuffix(serverURL, "/"))
	synapseResp, err := client.Get(synapseURL)
	if err == nil && synapseResp.StatusCode == http.StatusOK {
		synapseResp.Body.Close()
		return MatrixServerTypeSynapse, nil
	}
	if synapseResp != nil {
		synapseResp.Body.Close()
	}
	
	// Check for Dendrite-specific patterns or default to auto-detection
	// For now, we'll default to Dendrite if we can't detect Synapse
	// This maintains backward compatibility
	return MatrixServerTypeDendrite, nil
}

// GetEffectiveServerType returns the effective server type based on configuration
func GetEffectiveServerType() MatrixServerType {
	settings := Config.MOVIE_CLUB.Matrix
	
	// If server type is explicitly set and not auto, use it
	if settings.ServerType != "" && settings.ServerType != MatrixServerTypeAuto {
		return settings.ServerType
	}
	
	// If server type is auto or not set, try to detect
	if settings.ServerURL != "" {
		detected, err := DetectMatrixServerType(settings.ServerURL)
		if err != nil {
			slog.Warn("Failed to auto-detect Matrix server type, defaulting to Dendrite", 
				"error", err, "server_url", settings.ServerURL)
			return MatrixServerTypeDendrite
		}
		
		slog.Info("Auto-detected Matrix server type", 
			"detected_type", detected, "server_url", settings.ServerURL)
		return detected
	}
	
	// Default to Dendrite for backward compatibility
	return MatrixServerTypeDendrite
}

// IsServerTypeSynapse checks if the current server is Synapse
func IsServerTypeSynapse() bool {
	return GetEffectiveServerType() == MatrixServerTypeSynapse
}

// IsServerTypeDendrite checks if the current server is Dendrite
func IsServerTypeDendrite() bool {
	return GetEffectiveServerType() == MatrixServerTypeDendrite
}

// Matrix user registration interface and implementations

// MatrixUserRegistrar defines the interface for Matrix user registration
type MatrixUserRegistrar interface {
	RegisterUser(username, password string, admin bool) (*SharedSecretRegistrationResponse, error)
	ValidateRegistrationCapability() error
	GetServerType() MatrixServerType
}

// DendriteRegistrar implements user registration for Dendrite servers
type DendriteRegistrar struct{}

// SynapseRegistrar implements user registration for Synapse servers  
type SynapseRegistrar struct{}

// GetMatrixRegistrar returns the appropriate registrar for the current server type
func GetMatrixRegistrar() MatrixUserRegistrar {
	serverType := GetEffectiveServerType()
	switch serverType {
	case MatrixServerTypeSynapse:
		return &SynapseRegistrar{}
	case MatrixServerTypeDendrite:
		return &DendriteRegistrar{}
	default:
		// Default to Dendrite for backward compatibility
		return &DendriteRegistrar{}
	}
}

// DendriteRegistrar implementation

func (d *DendriteRegistrar) GetServerType() MatrixServerType {
	return MatrixServerTypeDendrite
}

func (d *DendriteRegistrar) ValidateRegistrationCapability() error {
	return errors.New("shared secret registration has been removed")
}

func (d *DendriteRegistrar) RegisterUser(username, password string, admin bool) (*SharedSecretRegistrationResponse, error) {
	return nil, errors.New("shared secret registration has been removed")
}

// SynapseRegistrar implementation

func (s *SynapseRegistrar) GetServerType() MatrixServerType {
	return MatrixServerTypeSynapse
}

func (s *SynapseRegistrar) ValidateRegistrationCapability() error {
	return errors.New("shared secret registration has been removed")
}

func (s *SynapseRegistrar) RegisterUser(username, password string, admin bool) (*SharedSecretRegistrationResponse, error) {
	return nil, errors.New("shared secret registration has been removed")
}

// RegisterUserWithSharedSecret - DEPRECATED: Shared secret registration removed for simplicity
func RegisterUserWithSharedSecret(username, password string, admin bool) (*SharedSecretRegistrationResponse, error) {
	return nil, errors.New("shared secret registration has been removed - use Application Service or manual account linking")
}

// Shared secret registration functions

// generateNonce creates a unique nonce for shared secret registration
func generateNonce() (string, error) {
	// Generate timestamp + random hex for uniqueness
	// Use UTC to avoid timezone mismatch issues with Dendrite server
	timestamp := time.Now().UTC().Unix()
	randomBytes := make([]byte, 8)
	if _, err := rand.Read(randomBytes); err != nil {
		return "", fmt.Errorf("failed to generate random bytes: %w", err)
	}
	randomHex := hex.EncodeToString(randomBytes)
	return fmt.Sprintf("%d_%s", timestamp, randomHex), nil
}

// generateSharedSecretMAC creates HMAC-SHA1 signature for shared secret registration
func generateSharedSecretMAC(sharedSecret, nonce, username, password string, admin bool) (string, error) {
	if sharedSecret == "" {
		return "", errors.New("shared secret is empty")
	}
	
	// Determine admin flag
	adminFlag := "notadmin"
	if admin {
		adminFlag = "admin"
	}
	
	// Create message: nonce + \0 + username + \0 + password + \0 + admin_flag
	// Build message with actual null byte separators (not literal \x00 strings)
	var message bytes.Buffer
	message.WriteString(nonce)
	message.WriteByte(0)
	message.WriteString(username)
	message.WriteByte(0)
	message.WriteString(password)
	message.WriteByte(0)
	message.WriteString(adminFlag)
	
	// Generate HMAC-SHA1
	mac := hmac.New(sha1.New, []byte(sharedSecret))
	mac.Write(message.Bytes())
	
	return hex.EncodeToString(mac.Sum(nil)), nil
}

// getServerNonce fetches a nonce from the Matrix server for shared secret registration
func getServerNonce() (string, error) {
	// Make GET request to fetch nonce
	url := fmt.Sprintf("%s/_synapse/admin/v1/register", getMatrixServerURL())
	
	slog.Debug("Fetching nonce from Matrix server", "url", url)
	
	resp, err := http.Get(url)
	if err != nil {
		return "", fmt.Errorf("failed to fetch nonce: %w", err)
	}
	defer resp.Body.Close()
	
	// Read response body for debugging
	var responseBody bytes.Buffer
	if _, err := responseBody.ReadFrom(resp.Body); err != nil {
		return "", fmt.Errorf("failed to read nonce response: %w", err)
	}
	
	slog.Debug("Nonce request response", 
		"status", resp.StatusCode, 
		"body", responseBody.String())
	
	// Check status code
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("nonce request failed with status %d: %s", resp.StatusCode, responseBody.String())
	}
	
	// Parse response
	var nonceResponse SharedSecretNonceResponse
	if err := json.Unmarshal(responseBody.Bytes(), &nonceResponse); err != nil {
		return "", fmt.Errorf("failed to parse nonce response: %w", err)
	}
	
	if nonceResponse.Nonce == "" {
		return "", errors.New("server returned empty nonce")
	}
	
	slog.Debug("Fetched nonce from Matrix server", "nonce", nonceResponse.Nonce)
	return nonceResponse.Nonce, nil
}

// registerUserWithDendriteSharedSecret - DEPRECATED: Shared secret registration removed for simplicity
func registerUserWithDendriteSharedSecret(username, password string, admin bool) (*SharedSecretRegistrationResponse, error) {
	return nil, errors.New("dendrite shared secret registration has been removed")
}

// registerUserWithSynapseSharedSecret - DEPRECATED: Shared secret registration removed for simplicity
func registerUserWithSynapseSharedSecret(username, password string, admin bool) (*SharedSecretRegistrationResponse, error) {
	return nil, errors.New("synapse shared secret registration has been removed")
}

// Matrix admin API abstraction layer

// MatrixAdminAPI defines the interface for Matrix admin operations
type MatrixAdminAPI interface {
	ResetUserPassword(matrixUserID, newPassword string) error
	RevokeUserTokens(matrixUserID string) error
	DeactivateUser(matrixUserID string) error
	GetServerInfo() (*MatrixServerInfo, error)
	GetServerType() MatrixServerType
}

// DendriteAdminAPI implements admin operations for Dendrite servers
type DendriteAdminAPI struct{}

// SynapseAdminAPI implements admin operations for Synapse servers
type SynapseAdminAPI struct{}

// GetMatrixAdminAPI returns the appropriate admin API for the current server type
func GetMatrixAdminAPI() MatrixAdminAPI {
	serverType := GetEffectiveServerType()
	switch serverType {
	case MatrixServerTypeSynapse:
		return &SynapseAdminAPI{}
	case MatrixServerTypeDendrite:
		return &DendriteAdminAPI{}
	default:
		// Default to Dendrite for backward compatibility
		return &DendriteAdminAPI{}
	}
}

// DendriteAdminAPI implementation

func (d *DendriteAdminAPI) GetServerType() MatrixServerType {
	return MatrixServerTypeDendrite
}

func (d *DendriteAdminAPI) GetServerInfo() (*MatrixServerInfo, error) {
	return &MatrixServerInfo{
		ServerType: MatrixServerTypeDendrite,
		ServerName: Config.MOVIE_CLUB.Matrix.ServerName,
		Version:    "unknown",
		Capabilities: []string{"shared_secret_registration"},
	}, nil
}

func (d *DendriteAdminAPI) ResetUserPassword(matrixUserID, newPassword string) error {
	// Dendrite doesn't have a direct password reset API
	// This is typically handled through shared secret registration
	return fmt.Errorf("password reset not supported directly on Dendrite - use account recreation")
}

func (d *DendriteAdminAPI) RevokeUserTokens(matrixUserID string) error {
	// Dendrite doesn't have a token revocation API
	// Tokens are typically revoked through user deactivation
	return fmt.Errorf("token revocation not supported directly on Dendrite")
}

func (d *DendriteAdminAPI) DeactivateUser(matrixUserID string) error {
	// Dendrite doesn't have a user deactivation API
	// Users are typically soft-deleted in the application layer
	return fmt.Errorf("user deactivation not supported directly on Dendrite")
}

// SynapseAdminAPI implementation

func (s *SynapseAdminAPI) GetServerType() MatrixServerType {
	return MatrixServerTypeSynapse
}

func (s *SynapseAdminAPI) GetServerInfo() (*MatrixServerInfo, error) {
	// Try to get server version from Synapse admin API
	url := fmt.Sprintf("%s/_synapse/admin/v1/server_version", getMatrixServerURL())
	
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create server info request: %w", err)
	}
	
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", Config.MOVIE_CLUB.Matrix.AdminToken))
	
	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to get server info: %w", err)
	}
	defer resp.Body.Close()
	
	if resp.StatusCode != http.StatusOK {
		return &MatrixServerInfo{
			ServerType: MatrixServerTypeSynapse,
			ServerName: Config.MOVIE_CLUB.Matrix.ServerName,
			Version:    "unknown",
			Capabilities: []string{"shared_secret_registration", "admin_api"},
		}, nil
	}
	
	var serverInfo struct {
		ServerVersion string `json:"server_version"`
		PythonVersion string `json:"python_version"`
	}
	
	if err := json.NewDecoder(resp.Body).Decode(&serverInfo); err != nil {
		return nil, fmt.Errorf("failed to parse server info: %w", err)
	}
	
	return &MatrixServerInfo{
		ServerType: MatrixServerTypeSynapse,
		ServerName: Config.MOVIE_CLUB.Matrix.ServerName,
		Version:    serverInfo.ServerVersion,
		Capabilities: []string{"shared_secret_registration", "admin_api", "user_management"},
	}, nil
}

func (s *SynapseAdminAPI) ResetUserPassword(matrixUserID, newPassword string) error {
	errContext := map[string]interface{}{
		"matrix_user_id": matrixUserID,
		"server_type": "synapse",
	}
	
	// Use Synapse admin API to reset password
	url := fmt.Sprintf("%s/_synapse/admin/v2/users/%s", getMatrixServerURL(), matrixUserID)
	
	// Build request body
	requestBody := map[string]interface{}{
		"password": newPassword,
		"logout_devices": false,
	}
	
	requestJSON, err := json.Marshal(requestBody)
	if err != nil {
		return logAndReturnError("synapse_password_reset_json_marshal", err, errContext)
	}
	
	// Create HTTP request
	req, err := http.NewRequest("PUT", url, bytes.NewBuffer(requestJSON))
	if err != nil {
		return logAndReturnError("synapse_password_reset_request_creation", err, errContext)
	}
	
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", Config.MOVIE_CLUB.Matrix.AdminToken))
	
	// Make request
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return logAndReturnError("synapse_password_reset_http_request", err, errContext)
	}
	defer resp.Body.Close()
	
	// Check response
	if resp.StatusCode == http.StatusOK || resp.StatusCode == http.StatusCreated {
		slog.Info("Successfully reset Matrix user password using Synapse admin API", 
			"matrix_user_id", matrixUserID)
		return nil
	} else {
		var responseBody bytes.Buffer
		responseBody.ReadFrom(resp.Body)
		return logAndReturnError("synapse_password_reset_failed", 
			fmt.Errorf("password reset failed with status %d: %s", resp.StatusCode, responseBody.String()), 
			errContext)
	}
}

func (s *SynapseAdminAPI) RevokeUserTokens(matrixUserID string) error {
	errContext := map[string]interface{}{
		"matrix_user_id": matrixUserID,
		"server_type": "synapse",
	}
	
	// Use Synapse admin API to revoke user tokens
	url := fmt.Sprintf("%s/_synapse/admin/v1/users/%s/devices", getMatrixServerURL(), matrixUserID)
	
	req, err := http.NewRequest("DELETE", url, nil)
	if err != nil {
		return logAndReturnError("synapse_token_revocation_request_creation", err, errContext)
	}
	
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", Config.MOVIE_CLUB.Matrix.AdminToken))
	
	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return logAndReturnError("synapse_token_revocation_http_request", err, errContext)
	}
	defer resp.Body.Close()
	
	if resp.StatusCode == http.StatusOK {
		slog.Info("Successfully revoked Matrix user tokens using Synapse admin API", 
			"matrix_user_id", matrixUserID)
		return nil
	} else {
		return logAndReturnError("synapse_token_revocation_failed", 
			fmt.Errorf("token revocation failed with status %d", resp.StatusCode), 
			errContext)
	}
}

func (s *SynapseAdminAPI) DeactivateUser(matrixUserID string) error {
	errContext := map[string]interface{}{
		"matrix_user_id": matrixUserID,
		"server_type": "synapse",
	}
	
	// Use Synapse admin API to deactivate user
	url := fmt.Sprintf("%s/_synapse/admin/v2/users/%s", getMatrixServerURL(), matrixUserID)
	
	// Build request body
	requestBody := map[string]interface{}{
		"deactivated": true,
	}
	
	requestJSON, err := json.Marshal(requestBody)
	if err != nil {
		return logAndReturnError("synapse_deactivation_json_marshal", err, errContext)
	}
	
	// Create HTTP request
	req, err := http.NewRequest("PUT", url, bytes.NewBuffer(requestJSON))
	if err != nil {
		return logAndReturnError("synapse_deactivation_request_creation", err, errContext)
	}
	
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", Config.MOVIE_CLUB.Matrix.AdminToken))
	
	// Make request
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return logAndReturnError("synapse_deactivation_http_request", err, errContext)
	}
	defer resp.Body.Close()
	
	// Check response
	if resp.StatusCode == http.StatusOK || resp.StatusCode == http.StatusCreated {
		slog.Info("Successfully deactivated Matrix user using Synapse admin API", 
			"matrix_user_id", matrixUserID)
		return nil
	} else {
		var responseBody bytes.Buffer
		responseBody.ReadFrom(resp.Body)
		return logAndReturnError("synapse_deactivation_failed", 
			fmt.Errorf("user deactivation failed with status %d: %s", resp.StatusCode, responseBody.String()), 
			errContext)
	}
}

// ReactivateMatrixAccount creates a new Matrix account for reactivation since Dendrite doesn't support true reactivation
func ReactivateMatrixAccount(matrixUserID, newPassword string) (*SharedSecretRegistrationResponse, error) {
	errContext := map[string]interface{}{
		"matrix_user_id": matrixUserID,
	}
	
	// Extract the localpart from the Matrix user ID
	// Format: @localpart:server.name
	if !strings.HasPrefix(matrixUserID, "@") || !strings.Contains(matrixUserID, ":") {
		return nil, logAndReturnError("invalid_matrix_user_id", 
			fmt.Errorf("invalid Matrix user ID format: %s", matrixUserID), errContext)
	}
	
	parts := strings.SplitN(matrixUserID[1:], ":", 2) // Remove @ and split on first :
	if len(parts) != 2 {
		return nil, logAndReturnError("invalid_matrix_user_id", 
			fmt.Errorf("could not parse Matrix user ID: %s", matrixUserID), errContext)
	}
	
	localpart := parts[0]
	serverName := parts[1]
	
	slog.Info("Attempting Matrix account reactivation by creating new account variant", 
		"original_matrix_user_id", matrixUserID,
		"original_localpart", localpart,
		"server_name", serverName)
	
	// Since Dendrite doesn't support true reactivation of deactivated accounts,
	// we'll create a new account with a suffix and store the original user ID in the database
	// The user will see the original user ID but internally we use the new one
	
	// Try creating accounts with incremental suffixes until we find one that works
	for attempt := 1; attempt <= 10; attempt++ {
		var newLocalpart string
		if attempt == 1 {
			// First try with "_reactivated" suffix
			newLocalpart = localpart + "_reactivated"
		} else {
			// Then try with numbered suffixes
			newLocalpart = fmt.Sprintf("%s_reactivated_%d", localpart, attempt-1)
		}
		
		slog.Info("Attempting reactivation with new localpart", 
			"attempt", attempt,
			"new_localpart", newLocalpart,
			"original_matrix_user_id", matrixUserID)
		
		registrationResponse, err := RegisterUserWithSharedSecret(newLocalpart, newPassword, false)
		if err != nil {
			if strings.Contains(err.Error(), "M_USER_IN_USE") {
				slog.Info("Localpart still in use, trying next variant", 
					"attempted_localpart", newLocalpart,
					"attempt", attempt)
				continue // Try next suffix
			}
			
			// Non-conflict error, fail immediately
			return nil, logAndReturnError("reactivation_registration_failed", fmt.Errorf(
				"failed to register new Matrix account for reactivation: %w", err), errContext)
		}
		
		// Success! We created a new Matrix account
		slog.Info("Successfully created new Matrix account for reactivation", 
			"original_matrix_user_id", matrixUserID,
			"new_matrix_user_id", registrationResponse.UserID,
			"attempt", attempt)
		
		// Return the response but we'll store the original user ID in the database for UI consistency
		return registrationResponse, nil
	}
	
	// If we get here, we tried 10 different suffixes and they were all taken
	return nil, logAndReturnError("reactivation_all_variants_taken", 
		errors.New("could not find available Matrix user ID variant for reactivation after 10 attempts"), errContext)
}


// resetMatrixUserPassword uses standard Matrix client API to change password
// resetMatrixUserPasswordSynapse fallback using Synapse admin API
func resetMatrixUserPasswordSynapse(matrixUserID, newPassword string) error {
	errContext := map[string]interface{}{
		"matrix_user_id": matrixUserID,
		"fallback": "synapse_api",
	}
	
	// Use Synapse admin API as fallback
	url := fmt.Sprintf("%s/_synapse/admin/v2/users/%s", getMatrixServerURL(), matrixUserID)
	
	// Build request body
	requestBody := map[string]interface{}{
		"password": newPassword,
		"logout_devices": false,
	}
	
	requestJSON, err := json.Marshal(requestBody)
	if err != nil {
		return logAndReturnError("json_marshal", err, errContext)
	}
	
	// Create HTTP request
	req, err := http.NewRequest("PUT", url, bytes.NewBuffer(requestJSON))
	if err != nil {
		return logAndReturnError("request_creation", err, errContext)
	}
	
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", Config.MOVIE_CLUB.Matrix.AdminToken))
	
	// Make request
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return logAndReturnError("http_request", err, errContext)
	}
	defer resp.Body.Close()
	
	// Read response
	var responseBody bytes.Buffer
	if _, err := responseBody.ReadFrom(resp.Body); err != nil {
		return logAndReturnError("response_read", err, errContext)
	}
	
	// Check response
	if resp.StatusCode == http.StatusOK || resp.StatusCode == http.StatusCreated {
		slog.Info("Successfully reset Matrix user password using Synapse API fallback", "matrix_user_id", matrixUserID)
		return nil
	} else {
		return logAndReturnError("password_reset_failed", 
			fmt.Errorf("password reset failed with status %d: %s", resp.StatusCode, responseBody.String()), 
			errContext)
	}
}

// resetMatrixUserPassword resets a Matrix user password using the appropriate admin API
func resetMatrixUserPassword(matrixUserID, newPassword string) error {
	adminAPI := GetMatrixAdminAPI()
	
	slog.Debug("Attempting Matrix user password reset", 
		"matrix_user_id", matrixUserID, 
		"server_type", adminAPI.GetServerType())
	
	return adminAPI.ResetUserPassword(matrixUserID, newPassword)
}

// ExportMatrixCredentials exports Matrix credentials for auto-generated users
func ExportMatrixCredentials(db *gorm.DB, watcharrUserID uint, deletePasswordAfterExport bool) (*MatrixCredentialExport, error) {
	errContext := map[string]interface{}{
		"watcharr_user_id": watcharrUserID,
	}

	// Get the Matrix user
	var matrixUser MatrixUser
	if err := db.Where("user_id = ?", watcharrUserID).First(&matrixUser).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("no Matrix account linked for this user")
		}
		return nil, logAndReturnError("database_find", err, errContext)
	}

	errContext["matrix_user_id"] = matrixUser.MatrixUserID
	errContext["is_auto_generated"] = matrixUser.IsAutoGenerated

	// Security check: Only allow export for auto-generated accounts
	if !matrixUser.IsAutoGenerated {
		return nil, logAndReturnError("credential_export_denied", 
			errors.New("credential export is only available for auto-generated Matrix accounts"), 
			errContext)
	}

	// Security check: Ensure password is available
	if matrixUser.EncryptedPassword == "" {
		return nil, logAndReturnError("no_password_available", 
			errors.New("no password available for export - account may be a placeholder"), 
			errContext)
	}

	// Rate limiting: Check export count (max 10 exports total, max 3 per hour)
	if matrixUser.PasswordExportCount >= 10 {
		return nil, logAndReturnError("export_limit_exceeded", 
			errors.New("maximum number of password exports exceeded for security"), 
			errContext)
	}

	// Check if exported recently (within last 5 minutes)
	if matrixUser.PasswordExportedAt != nil {
		fiveMinutesAgo := time.Now().Add(-5 * time.Minute)
		if matrixUser.PasswordExportedAt.After(fiveMinutesAgo) {
			// Limit to one export per 5 minutes
			return nil, logAndReturnError("export_rate_limited", 
				fmt.Errorf("password was exported recently at %s - please wait at least 5 minutes between exports", 
					matrixUser.PasswordExportedAt.Format("2006-01-02 15:04:05")), 
				errContext)
		}
	}

	// Decrypt the password
	password, err := decryptToken(matrixUser.EncryptedPassword)
	if err != nil {
		// If decryption fails, it's likely due to encryption key change after server restart
		// Provide a helpful error message
		return nil, logAndReturnError("password_decryption", 
			fmt.Errorf("failed to decrypt password - this may be due to server restart. Please recreate your Matrix account: %w", err), 
			errContext)
	}

	// Create export response
	export := &MatrixCredentialExport{
		MatrixUserID: matrixUser.MatrixUserID,
		Password:     password,
		ServerURL:    Config.MOVIE_CLUB.Matrix.ServerURL,
		ServerName:   Config.MOVIE_CLUB.Matrix.ServerName,
		ExportedAt:   time.Now(),
	}

	// Update export tracking
	now := time.Now()
	matrixUser.PasswordExported = true
	matrixUser.PasswordExportedAt = &now
	matrixUser.PasswordExportCount++

	// Optionally delete password after export for enhanced security
	if deletePasswordAfterExport {
		matrixUser.EncryptedPassword = ""
		slog.Info("Password deleted after export for enhanced security", 
			"watcharr_user_id", watcharrUserID,
			"matrix_user_id", matrixUser.MatrixUserID)
	}

	// Save changes
	if err := db.Save(&matrixUser).Error; err != nil {
		return nil, logAndReturnError("export_tracking_update", err, errContext)
	}

	slog.Info("Matrix credentials exported", 
		"watcharr_user_id", watcharrUserID,
		"matrix_user_id", matrixUser.MatrixUserID,
		"export_count", matrixUser.PasswordExportCount,
		"password_deleted", deletePasswordAfterExport)

	return export, nil
}

// MatrixCredentialExport represents exported Matrix credentials
type MatrixCredentialExport struct {
	MatrixUserID string    `json:"matrixUserId"`
	Password     string    `json:"password"`
	ServerURL    string    `json:"serverUrl"`
	ServerName   string    `json:"serverName"`
	ExportedAt   time.Time `json:"exportedAt"`
}

// revokeUserTokens attempts to revoke all access tokens for a Matrix user
func revokeUserTokens(matrixUserID string) error {
	adminAPI := GetMatrixAdminAPI()
	
	slog.Debug("Attempting Matrix user token revocation", 
		"matrix_user_id", matrixUserID, 
		"server_type", adminAPI.GetServerType())
	
	return adminAPI.RevokeUserTokens(matrixUserID)
}

// DeactivateMatrixUser deactivates a Matrix user using the standard Matrix client API
func DeactivateMatrixUser(db *gorm.DB, matrixUserID string) error {
	errContext := map[string]interface{}{
		"matrix_user_id": matrixUserID,
	}
	
	// Get user's stored access token and password from database
	var matrixUser MatrixUser
	if err := db.Where("matrix_user_id = ?", matrixUserID).First(&matrixUser).Error; err != nil {
		// User not found in database, skip deactivation
		return nil
	}
	
	// Only attempt deactivation for auto-generated users with stored credentials
	if !matrixUser.IsAutoGenerated {
		return nil
	}
	
	// Decrypt access token
	accessToken, err := decryptToken(matrixUser.AccessToken)
	if err != nil {
		slog.Warn("Could not decrypt access token for Matrix user deactivation", 
			"matrix_user_id", matrixUserID, "error", err)
		return nil // Don't fail the unlink operation
	}
	
	// Decrypt password if available
	var password string
	if matrixUser.EncryptedPassword != "" {
		password, err = decryptToken(matrixUser.EncryptedPassword)
		if err != nil {
			slog.Warn("Could not decrypt password for Matrix user deactivation", 
				"matrix_user_id", matrixUserID, "error", err)
			// Continue without password - try token-only deactivation
		}
	}
	
	// Use standard Matrix client API for deactivation
	url := fmt.Sprintf("%s/_matrix/client/r0/account/deactivate", getMatrixServerURL())
	
	// Build request body with authentication
	requestBody := map[string]interface{}{
		"erase": true, // Remove user data completely
	}
	
	// Add password authentication if available
	if password != "" {
		requestBody["auth"] = map[string]interface{}{
			"type":     "m.login.password",
			"user":     matrixUserID,
			"password": password,
		}
	}
	
	requestJSON, err := json.Marshal(requestBody)
	if err != nil {
		return logAndReturnError("json_marshal", err, errContext)
	}
	
	// Create HTTP request
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(requestJSON))
	if err != nil {
		return logAndReturnError("request_creation", err, errContext)
	}
	
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", accessToken))
	
	// Make request
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return logAndReturnError("http_request", err, errContext)
	}
	defer resp.Body.Close()
	
	// Read response
	var responseBody bytes.Buffer
	if _, err := responseBody.ReadFrom(resp.Body); err != nil {
		return logAndReturnError("response_read", err, errContext)
	}
	
	// Check response
	if resp.StatusCode == http.StatusOK {
		slog.Info("Successfully deactivated Matrix user", "matrix_user_id", matrixUserID)
		return nil
	} else if resp.StatusCode == http.StatusUnauthorized {
		// Need additional authentication - this happens with UIA (User Interactive Authentication)
		var uiaResponse map[string]interface{}
		if err := json.Unmarshal(responseBody.Bytes(), &uiaResponse); err == nil {
			if session, ok := uiaResponse["session"].(string); ok && session != "" {
				// Matrix deactivation requires UIA session
				
				// Try deactivation with UIA session
				return completeMatrixDeactivationUIA(matrixUserID, session, password, accessToken)
			}
		}
		
		slog.Warn("Matrix user deactivation failed - authentication required", 
			"matrix_user_id", matrixUserID,
			"note", "Manual deactivation may be required")
		return nil // Don't fail the unlink operation
	} else if resp.StatusCode == http.StatusNotFound {
		slog.Warn("Matrix deactivation endpoint not available", 
			"matrix_user_id", matrixUserID,
			"note", "Manual deactivation may be required")
		return nil // Don't treat this as an error
	} else {
		slog.Warn("Matrix user deactivation failed", 
			"matrix_user_id", matrixUserID,
			"status", resp.StatusCode,
			"response", responseBody.String(),
			"note", "Manual deactivation may be required")
		return nil // Don't fail the unlink operation for deactivation issues
	}
}

// completeMatrixDeactivationUIA completes Matrix user deactivation using User Interactive Authentication
func completeMatrixDeactivationUIA(matrixUserID, session, password, accessToken string) error {
	if password == "" {
		slog.Warn("Cannot complete UIA deactivation without password", "matrix_user_id", matrixUserID)
		return nil
	}
	
	url := fmt.Sprintf("%s/_matrix/client/r0/account/deactivate", getMatrixServerURL())
	
	requestBody := map[string]interface{}{
		"erase": true,
		"auth": map[string]interface{}{
			"type":     "m.login.password",
			"user":     matrixUserID,
			"password": password,
			"session":  session,
		},
	}
	
	requestJSON, err := json.Marshal(requestBody)
	if err != nil {
		return fmt.Errorf("failed to marshal UIA request: %w", err)
	}
	
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(requestJSON))
	if err != nil {
		return fmt.Errorf("failed to create UIA request: %w", err)
	}
	
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", accessToken))
	
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("UIA request failed: %w", err)
	}
	defer resp.Body.Close()
	
	if resp.StatusCode == http.StatusOK {
		slog.Info("Successfully completed Matrix user deactivation via UIA", "matrix_user_id", matrixUserID)
		return nil
	}
	
	// Read response for debugging
	var responseBody bytes.Buffer
	responseBody.ReadFrom(resp.Body)
	
	slog.Warn("Matrix UIA deactivation failed", 
		"matrix_user_id", matrixUserID,
		"status", resp.StatusCode,
		"response", responseBody.String())
	
	return nil // Don't fail the unlink operation
}

// Matrix Application Service Registration File Generation

// ASRegistrationFile represents the YAML structure for Matrix AS registration
type ASRegistrationFile struct {
	ID              string                    `yaml:"id"`
	URL             string                    `yaml:"url"`
	AppServiceToken string                    `yaml:"as_token"`
	HomeServerToken string                    `yaml:"hs_token"`
	SenderLocalpart string                    `yaml:"sender_localpart"`
	Namespaces      ASRegistrationNamespaces  `yaml:"namespaces"`
	RateLimited     bool                      `yaml:"rate_limited"`
}

// ASRegistrationNamespaces represents the namespaces section of AS registration
type ASRegistrationNamespaces struct {
	Users   []ASNamespaceRule `yaml:"users"`
	Aliases []ASNamespaceRule `yaml:"aliases"`
}

// ASNamespaceRule represents a single namespace rule
type ASNamespaceRule struct {
	Exclusive bool   `yaml:"exclusive"`
	Regex     string `yaml:"regex"`
}

// generateSecureToken creates a cryptographically secure random token
func generateSecureToken() (string, error) {
	bytes := make([]byte, 32) // 256-bit token
	if _, err := rand.Read(bytes); err != nil {
		return "", fmt.Errorf("failed to generate secure token: %w", err)
	}
	return hex.EncodeToString(bytes), nil
}

// getWatcharrURL attempts to determine the Watcharr server URL
func getWatcharrURL() string {
	// Try to determine from Matrix server URL (common in same-host deployments)
	if Config.MOVIE_CLUB.Matrix.ServerURL != "" {
		serverURL := Config.MOVIE_CLUB.Matrix.ServerURL
		// If Matrix is on same host, try common Watcharr ports
		if strings.Contains(serverURL, ":8008") {
			return strings.Replace(serverURL, ":8008", ":8080", 1)
		}
		if strings.Contains(serverURL, ":8448") {
			return strings.Replace(serverURL, ":8448", ":8080", 1)
		}
		// Remove port and add :8080
		if colonIndex := strings.LastIndex(serverURL, ":"); colonIndex != -1 {
			baseURL := serverURL[:colonIndex]
			return baseURL + ":8080"
		}
	}
	
	// Default fallback
	return "http://watcharr:8080"
}

// ensureASTokensGenerated ensures AS tokens are generated if missing
func ensureASTokensGenerated(asSettings *AppServiceSettings) error {
	changed := false
	
	if asSettings.AppServiceToken == "" {
		token, err := generateSecureToken()
		if err != nil {
			return fmt.Errorf("failed to generate AS token: %w", err)
		}
		asSettings.AppServiceToken = token
		changed = true
		slog.Info("Auto-generated Application Service token")
	}
	
	if asSettings.HomeServerToken == "" {
		token, err := generateSecureToken()
		if err != nil {
			return fmt.Errorf("failed to generate HS token: %w", err)
		}
		asSettings.HomeServerToken = token
		changed = true
		slog.Info("Auto-generated HomeServer token")
	}
	
	// Set default values for other fields if not configured
	if asSettings.ID == "" {
		asSettings.ID = "watcharr-movieclub"
		changed = true
	}
	
	if asSettings.SenderLocalpart == "" {
		asSettings.SenderLocalpart = "watcharr-bot"
		changed = true
	}
	
	if changed {
		// Save updated configuration to file
		if err := writeConfig(); err != nil {
			slog.Warn("Failed to save auto-generated AS tokens to config file", "error", err)
		}
	}
	
	return nil
}

// GenerateASRegistrationFile creates the Matrix Application Service registration YAML file
func GenerateASRegistrationFile(asSettings *AppServiceSettings, matrixSettings *MatrixSettings) (string, error) {
	if !asSettings.Enabled {
		return "", errors.New("Application Service is not enabled")
	}
	
	// Ensure tokens are generated
	if err := ensureASTokensGenerated(asSettings); err != nil {
		return "", fmt.Errorf("failed to ensure AS tokens: %w", err)
	}
	
	// Determine Watcharr URL
	watcharrURL := getWatcharrURL()
	
	// Generate namespaces based on server name
	serverName := matrixSettings.ServerName
	if serverName == "" {
		return "", errors.New("Matrix server name is required for namespace generation")
	}
	
	// Auto-generate namespaces if not provided
	userNamespace := asSettings.UserNamespace
	if userNamespace == "" {
		userNamespace = fmt.Sprintf("@watcharr_.*:%s", serverName)
	}
	
	aliasNamespace := asSettings.AliasNamespace
	if aliasNamespace == "" {
		aliasNamespace = fmt.Sprintf("#watcharr_.*:%s", serverName)
	}
	
	// Create registration file structure
	regFile := ASRegistrationFile{
		ID:              asSettings.ID,
		URL:             watcharrURL,
		AppServiceToken: asSettings.AppServiceToken,
		HomeServerToken: asSettings.HomeServerToken,
		SenderLocalpart: asSettings.SenderLocalpart,
		Namespaces: ASRegistrationNamespaces{
			Users: []ASNamespaceRule{
				{
					Exclusive: true,
					Regex:     userNamespace,
				},
			},
			Aliases: []ASNamespaceRule{
				{
					Exclusive: true,
					Regex:     aliasNamespace,
				},
			},
		},
		RateLimited: asSettings.RateLimited,
	}
	
	// Convert to YAML
	yamlBytes, err := yaml.Marshal(&regFile)
	if err != nil {
		return "", fmt.Errorf("failed to marshal registration file to YAML: %w", err)
	}
	
	// Add header comment
	header := `# Matrix Application Service Registration File for Watcharr
# Generated automatically by Watcharr
# Place this file in your Matrix server's Application Service configuration directory
# and reference it in your Matrix server configuration file.
#
# For Dendrite: Add to app_service_api.config_files in dendrite.yaml
# For Synapse: Add to app_service_config_files in homeserver.yaml

`
	
	return header + string(yamlBytes), nil
}

