package main

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"regexp"
	"strings"
	"time"

	"maunium.net/go/mautrix"
	"maunium.net/go/mautrix/event"
	"maunium.net/go/mautrix/id"
	"gorm.io/gorm"
)

// Matrix database models

// MatrixUser stores Matrix user mappings for Watcharr users
type MatrixUser struct {
	GormModel
	UserID            uint   `json:"userId" gorm:"index"`
	MatrixUserID      string `json:"matrixUserId" gorm:"unique"` // @username:server.name
	IsAutoGenerated   bool   `json:"isAutoGenerated" gorm:"default:true"`
	AccessToken       string `json:"accessToken"`       // Encrypted access token
	DeviceID          string `json:"deviceId"`          // Matrix device ID
	User              User   `json:"user,omitempty" gorm:"foreignKey:UserID"`
}

// MatrixRoom stores Matrix rooms for movie club cycles
type MatrixRoom struct {
	GormModel
	CycleID   uint               `json:"cycleId" gorm:"index"`
	RoomID    string             `json:"roomId" gorm:"unique"`    // !room_id:server.name
	RoomAlias string             `json:"roomAlias"`               // #cycle-1-movie-name:server.name
	Cycle     MovieClubCycle     `json:"cycle,omitempty" gorm:"foreignKey:CycleID"`
	Members   []MatrixRoomMember `json:"members,omitempty" gorm:"foreignKey:RoomID"`
}

// MatrixRoomMember tracks room memberships
type MatrixRoomMember struct {
	GormModel
	RoomID     uint       `json:"roomId" gorm:"index"`
	UserID     uint       `json:"userId" gorm:"index"`
	JoinedAt   time.Time  `json:"joinedAt" gorm:"default:CURRENT_TIMESTAMP"`
	Room       MatrixRoom `json:"room,omitempty" gorm:"foreignKey:RoomID"`
	User       User       `json:"user,omitempty" gorm:"foreignKey:UserID"`
}

// MatrixSpace stores the Movie Club space information
type MatrixSpace struct {
	GormModel
	SpaceID   string `json:"spaceId" gorm:"unique"` // !space_id:server.name
	SpaceName string `json:"spaceName"`
}

// Matrix client management

var matrixClient *mautrix.Client

// InitializeMatrixClient creates and configures the Matrix client
func InitializeMatrixClient() error {
	if !Config.MOVIE_CLUB.Matrix.Enabled {
		slog.Debug("Matrix integration is disabled")
		return nil
	}

	settings := Config.MOVIE_CLUB.Matrix
	if settings.ServerURL == "" || settings.AdminToken == "" {
		return errors.New("matrix configuration incomplete: missing server URL or admin token")
	}

	// Create Matrix client
	client, err := mautrix.NewClient(settings.ServerURL, "", "")
	if err != nil {
		return fmt.Errorf("failed to create Matrix client: %w", err)
	}

	// Set admin access token
	client.AccessToken = settings.AdminToken
	
	matrixClient = client
	
	// Test connection
	if err := testMatrixConnection(); err != nil {
		return fmt.Errorf("matrix connection test failed: %w", err)
	}

	slog.Info("Matrix client initialized successfully", "server", settings.ServerURL)
	return nil
}

// testMatrixConnection verifies the Matrix connection and admin permissions
func testMatrixConnection() error {
	if matrixClient == nil {
		return errors.New("matrix client not initialized")
	}

	// Test with a simple whoami request
	resp, err := matrixClient.Whoami()
	if err != nil {
		return fmt.Errorf("failed to authenticate with Matrix server: %w", err)
	}

	slog.Debug("Matrix connection test successful", "user_id", resp.UserID)
	return nil
}

// User management functions

// CreateMatrixUser creates a new Matrix user for a Watcharr user
func CreateMatrixUser(watcharrUserID uint, username string) (*MatrixUser, error) {
	if matrixClient == nil {
		return nil, errors.New("matrix client not initialized")
	}

	// Generate Matrix user ID
	serverName := Config.MOVIE_CLUB.Matrix.ServerName
	matrixUserID := fmt.Sprintf("@watcharr_%d_%s:%s", watcharrUserID, username, serverName)

	// Generate random password
	password, err := generateRandomPassword()
	if err != nil {
		return nil, fmt.Errorf("failed to generate password: %w", err)
	}

	// Create user on Matrix server
	req := &mautrix.ReqCreateUser{
		Username: strings.TrimPrefix(matrixUserID, "@"),
		Password: password,
	}

	resp, err := matrixClient.CreateUser(req)
	if err != nil {
		return nil, fmt.Errorf("failed to create Matrix user: %w", err)
	}

	// Login to get access token
	loginResp, err := matrixClient.Login(&mautrix.ReqLogin{
		Type:     "m.login.password",
		User:     matrixUserID,
		Password: password,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to login as new Matrix user: %w", err)
	}

	// Store in database
	matrixUser := &MatrixUser{
		UserID:          watcharrUserID,
		MatrixUserID:    resp.UserID.String(),
		IsAutoGenerated: true,
		AccessToken:     loginResp.AccessToken, // TODO: Encrypt this
		DeviceID:        loginResp.DeviceID.String(),
	}

	if err := DB.Create(matrixUser).Error; err != nil {
		return nil, fmt.Errorf("failed to store Matrix user: %w", err)
	}

	slog.Info("Created Matrix user", "watcharr_user_id", watcharrUserID, "matrix_user_id", matrixUserID)
	return matrixUser, nil
}

// LinkCustomMatrixUser validates and links a custom Matrix user
func LinkCustomMatrixUser(watcharrUserID uint, matrixUserID string, accessToken string) error {
	// Validate Matrix user exists and token works
	if err := ValidateMatrixUser(matrixUserID, accessToken); err != nil {
		return fmt.Errorf("matrix user validation failed: %w", err)
	}

	// Remove auto-generated user if exists
	if err := RemoveAutoGeneratedUser(watcharrUserID); err != nil {
		slog.Warn("Failed to remove auto-generated user", "error", err)
	}

	// Store custom user mapping
	matrixUser := &MatrixUser{
		UserID:          watcharrUserID,
		MatrixUserID:    matrixUserID,
		IsAutoGenerated: false,
		AccessToken:     accessToken, // TODO: Encrypt this
	}

	if err := DB.Create(matrixUser).Error; err != nil {
		return fmt.Errorf("failed to store custom Matrix user: %w", err)
	}

	slog.Info("Linked custom Matrix user", "watcharr_user_id", watcharrUserID, "matrix_user_id", matrixUserID)
	return nil
}

// RemoveAutoGeneratedUser removes an auto-generated Matrix user
func RemoveAutoGeneratedUser(watcharrUserID uint) error {
	var matrixUser MatrixUser
	if err := DB.Where("user_id = ? AND is_auto_generated = true", watcharrUserID).First(&matrixUser).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil // No auto-generated user to remove
		}
		return err
	}

	// TODO: Deactivate user on Matrix server
	// For now, just remove from our database
	if err := DB.Delete(&matrixUser).Error; err != nil {
		return fmt.Errorf("failed to remove Matrix user from database: %w", err)
	}

	slog.Info("Removed auto-generated Matrix user", "watcharr_user_id", watcharrUserID, "matrix_user_id", matrixUser.MatrixUserID)
	return nil
}

// ValidateMatrixUser checks if a Matrix user exists and token is valid
func ValidateMatrixUser(matrixUserID, accessToken string) error {
	// Create temporary client with user's token
	tempClient, err := mautrix.NewClient(Config.MOVIE_CLUB.Matrix.ServerURL, id.UserID(matrixUserID), "")
	if err != nil {
		return fmt.Errorf("failed to create client: %w", err)
	}

	tempClient.AccessToken = accessToken

	// Test with whoami
	resp, err := tempClient.Whoami()
	if err != nil {
		return fmt.Errorf("failed to validate user: %w", err)
	}

	if resp.UserID.String() != matrixUserID {
		return errors.New("user ID mismatch")
	}

	return nil
}

// GetOrCreateMatrixUser gets existing Matrix user or creates one if needed
func GetOrCreateMatrixUser(watcharrUserID uint, username string) (*MatrixUser, error) {
	// Check if user already has Matrix account
	var matrixUser MatrixUser
	if err := DB.Where("user_id = ?", watcharrUserID).First(&matrixUser).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			// Create new Matrix user
			return CreateMatrixUser(watcharrUserID, username)
		}
		return nil, err
	}

	return &matrixUser, nil
}

// Utility functions

// generateRandomPassword creates a random password for Matrix users
func generateRandomPassword() (string, error) {
	bytes := make([]byte, 16)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}

// normalizeTitle normalizes movie titles for room aliases
func normalizeTitle(title string) string {
	// Convert to lowercase
	normalized := strings.ToLower(title)

	// Replace spaces and special chars with hyphens
	reg := regexp.MustCompile(`[^a-z0-9]+`)
	normalized = reg.ReplaceAllString(normalized, "-")

	// Remove leading/trailing hyphens
	normalized = strings.Trim(normalized, "-")

	// Limit length to 50 characters
	if len(normalized) > 50 {
		normalized = normalized[:50]
		normalized = strings.TrimSuffix(normalized, "-")
	}

	return normalized
}

// generateRoomAlias creates a room alias for a movie club cycle
func generateRoomAlias(cycle *MovieClubCycle) string {
	winDate := cycle.VotingEndDate.Format("2006-01-02")
	movieTitle := normalizeTitle(cycle.WinnerContent.Title)
	return fmt.Sprintf("%s-%s", winDate, movieTitle)
}