package main

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"maunium.net/go/mautrix"
	"maunium.net/go/mautrix/event"
	"maunium.net/go/mautrix/id"
	"gorm.io/gorm"
)

// Room creation and management functions

// CreateCycleRoom creates a Matrix room for a movie club cycle
func CreateCycleRoom(db *gorm.DB, cycle *MovieClubCycle) (*MatrixRoom, error) {
	if matrixClient == nil {
		return nil, errors.New("matrix client not initialized")
	}

	if !Config.MOVIE_CLUB.Matrix.Enabled {
		return nil, errors.New("matrix integration is disabled")
	}

	// Check if room already exists for this cycle
	var existingRoom MatrixRoom
	if err := db.Where("cycle_id = ?", cycle.ID).First(&existingRoom).Error; err == nil {
		slog.Debug("Room already exists for cycle", "cycle_id", cycle.ID, "room_id", existingRoom.RoomID)
		return &existingRoom, nil
	}

	// Generate room alias and name
	alias := generateRoomAlias(cycle)
	
	var movieTitle string
	if cycle.WinnerContent != nil {
		movieTitle = cycle.WinnerContent.Title
	} else {
		movieTitle = fmt.Sprintf("Cycle %d", cycle.ID)
	}
	
	roomName := fmt.Sprintf("Movie Club: %s (%s)",
		movieTitle,
		cycle.VotingEndDate.Format("2006-01-02"))

	// Create room configuration
	createReq := &mautrix.ReqCreateRoom{
		RoomAliasName: alias,
		Name:          roomName,
		Topic:         fmt.Sprintf("Discussion for %s - Movie Club Cycle", movieTitle),
		Preset:        "private_chat",
		Visibility:    "private",
		IsDirect:      false,
		// Note: Federate and PowerLevelContentOverride fields removed in SDK v0.21.0
		InitialState: []*event.Event{
			&event.Event{
				Type: event.StateTopic,
				Content: event.Content{
					Parsed: &event.TopicEventContent{
						Topic: fmt.Sprintf("Movie Club discussion for %s", movieTitle),
					},
				},
			},
		},
	}

	// Create the room
	resp, err := matrixClient.CreateRoom(context.Background(), createReq)
	if err != nil {
		return nil, fmt.Errorf("failed to create Matrix room: %w", err)
	}

	// Store room in database
	matrixRoom := &MatrixRoom{
		CycleID:   &cycle.ID,
		RoomID:    resp.RoomID.String(),
		RoomAlias: fmt.Sprintf("#%s:%s", alias, Config.MOVIE_CLUB.Matrix.ServerName),
		RoomName:  fmt.Sprintf("Movie Club - %s", cycle.WinnerContent.Title),
		RoomType:  MatrixRoomTypeGeneral, // Legacy single room becomes General
		SpaceID:   nil, // Legacy rooms don't have spaces initially
	}

	if err := db.Create(matrixRoom).Error; err != nil {
		return nil, fmt.Errorf("failed to store Matrix room: %w", err)
	}

	slog.Info("Created Matrix room for cycle",
		"cycle_id", cycle.ID,
		"room_id", resp.RoomID,
		"alias", matrixRoom.RoomAlias,
		"movie", movieTitle)

	// Add room to Movie Club space
	if err := AddRoomToMovieClubSpace(db, resp.RoomID.String()); err != nil {
		slog.Warn("Failed to add room to Movie Club space", "error", err, "room_id", resp.RoomID)
	}

	// Invite eligible users to the room
	if err := InviteUsersToRoom(db, cycle.ID); err != nil {
		slog.Warn("Failed to invite users to room", "error", err, "room_id", resp.RoomID)
	}

	return matrixRoom, nil
}

// InviteUsersToRoom invites all eligible users to a cycle room
func InviteUsersToRoom(db *gorm.DB, cycleID uint) error {
	if matrixClient == nil {
		return errors.New("matrix client not initialized")
	}

	// Get the room
	var room MatrixRoom
	if err := db.Where("cycle_id = ?", cycleID).First(&room).Error; err != nil {
		return fmt.Errorf("room not found for cycle %d: %w", cycleID, err)
	}

	// Get eligible users (those who nominated or voted in this cycle)
	eligibleUsers, err := GetEligibleUsersForCycle(db, cycleID)
	if err != nil {
		return fmt.Errorf("failed to get eligible users: %w", err)
	}

	roomID := id.RoomID(room.RoomID)
	successCount := 0
	errorCount := 0

	for _, user := range eligibleUsers {
		// Get Matrix user for this Watcharr user using hybrid system
		matrixUser, err := GetOrCreateMatrixUserV2(db, user.ID, user.Username)
		if err != nil {
			slog.Warn("Failed to get Matrix user for invitation",
				"watcharr_user_id", user.ID,
				"username", user.Username,
				"error", err)
			errorCount++
			continue
		}

		// Only invite real Matrix users (skip AS virtual users without external access)
		skipInvitation := false
		if matrixUser.AccountType == AccountTypeAppService {
			// AS users don't have external access, but they exist virtually
			skipInvitation = false // Actually invite them since they're real in the Matrix homeserver
		} else if matrixUser.AccountType == AccountTypePersonal && matrixUser.IsAutoGenerated {
			// Auto-generated personal accounts are placeholder only (shared secret registration removed)
			skipInvitation = true
		}
		
		if skipInvitation {
			slog.Info("Skipping invitation for placeholder Matrix user",
				"room_id", roomID,
				"matrix_user_id", matrixUser.MatrixUserID,
				"watcharr_user_id", user.ID,
				"account_type", matrixUser.AccountType,
				"note", "Use Application Service accounts or manually link existing Matrix accounts")
			continue
		}

		// Invite user to room
		_, err = matrixClient.InviteUser(context.Background(), roomID, &mautrix.ReqInviteUser{
			UserID: id.UserID(matrixUser.MatrixUserID),
		})

		if err != nil {
			slog.Warn("Failed to invite user to room",
				"matrix_user_id", matrixUser.MatrixUserID,
				"room_id", roomID,
				"error", err)
			errorCount++
			continue
		}

		// Record membership in database
		membership := &MatrixRoomMember{
			RoomID:   room.ID,
			UserID:   user.ID,
			JoinedAt: time.Now(),
		}

		if err := db.Create(membership).Error; err != nil {
			slog.Warn("Failed to record room membership", "error", err)
		}

		successCount++
		slog.Debug("Invited user to room",
			"matrix_user_id", matrixUser.MatrixUserID,
			"room_id", roomID)
	}

	slog.Info("Room invitation complete",
		"cycle_id", cycleID,
		"room_id", roomID,
		"invited", successCount,
		"errors", errorCount)

	return nil
}

// GetEligibleUsersForCycle returns users who participated in a cycle (nominated or voted)
func GetEligibleUsersForCycle(db *gorm.DB, cycleID uint) ([]User, error) {
	var users []User

	// Get users who nominated in this cycle
	err := db.Raw(`
		SELECT DISTINCT u.* FROM users u
		INNER JOIN movie_club_nominations mcn ON u.id = mcn.user_id
		WHERE mcn.cycle_id = ?
		UNION
		SELECT DISTINCT u.* FROM users u
		INNER JOIN movie_club_votes mcv ON u.id = mcv.user_id
		WHERE mcv.cycle_id = ?
	`, cycleID, cycleID).Scan(&users).Error

	if err != nil {
		return nil, fmt.Errorf("failed to get eligible users: %w", err)
	}

	return users, nil
}

// Movie Club Space Management

// EnsureMovieClubSpace creates or gets the Movie Club space
func EnsureMovieClubSpace(db *gorm.DB) (*MatrixSpace, error) {
	if matrixClient == nil {
		return nil, errors.New("matrix client not initialized")
	}

	// Check if Movie Club space already exists (specifically look for the main space)
	var existingSpace MatrixSpace
	if err := db.Where("space_type = ?", MatrixSpaceTypeMovieClub).First(&existingSpace).Error; err == nil {
		slog.Debug("Movie Club space already exists", "space_id", existingSpace.SpaceID, "name", existingSpace.SpaceName)
		return &existingSpace, nil
	}

	spaceName := Config.MOVIE_CLUB.Matrix.SpaceName
	if spaceName == "" {
		spaceName = "Movie Club"
	}

	// Create space
	createReq := &mautrix.ReqCreateRoom{
		Name:       spaceName,
		Topic:      "Movie Club discussions and activities",
		Preset:     "private_chat",
		Visibility: "private",
		CreationContent: map[string]interface{}{
			"type": "m.space",
		},
		// Note: Federate and PowerLevelContentOverride fields removed in SDK v0.21.0
	}

	resp, err := matrixClient.CreateRoom(context.Background(), createReq)
	if err != nil {
		return nil, fmt.Errorf("failed to create Movie Club space: %w", err)
	}

	// Store space in database
	space := &MatrixSpace{
		SpaceID:       resp.RoomID.String(),
		SpaceName:     spaceName,
		SpaceType:     MatrixSpaceTypeMovieClub,
		CycleID:       nil,           // Main space is not associated with any specific cycle
		ParentSpaceID: nil,           // Main space has no parent
	}

	if err := db.Create(space).Error; err != nil {
		return nil, fmt.Errorf("failed to store Movie Club space: %w", err)
	}

	slog.Info("Created Movie Club space", "space_id", resp.RoomID, "name", spaceName)
	return space, nil
}

// AddRoomToMovieClubSpace adds a room to the Movie Club space
func AddRoomToMovieClubSpace(db *gorm.DB, roomID string) error {
	if matrixClient == nil {
		return errors.New("matrix client not initialized")
	}

	// Ensure Movie Club space exists
	space, err := EnsureMovieClubSpace(db)
	if err != nil {
		return fmt.Errorf("failed to ensure Movie Club space: %w", err)
	}

	spaceID := id.RoomID(space.SpaceID)
	childRoomID := id.RoomID(roomID)

	// Add room as child of space
	stateKey := roomID
	content := map[string]interface{}{
		"via": []string{Config.MOVIE_CLUB.Matrix.ServerName},
	}
	_, err = matrixClient.SendStateEvent(context.Background(), spaceID, event.StateSpaceChild, stateKey, content)

	if err != nil {
		return fmt.Errorf("failed to add room to space: %w", err)
	}

	// Add space as parent of room
	parentContent := map[string]interface{}{
		"via": []string{Config.MOVIE_CLUB.Matrix.ServerName},
	}
	_, err = matrixClient.SendStateEvent(context.Background(), childRoomID, event.StateSpaceParent, space.SpaceID, parentContent)

	if err != nil {
		slog.Warn("Failed to set space as parent of room", "error", err)
		// Don't return error as the main relationship is established
	}

	slog.Debug("Added room to Movie Club space", "room_id", roomID, "space_id", space.SpaceID)
	return nil
}

// Room lifecycle management

// ArchiveOldRooms archives rooms for completed cycles (future enhancement)
func ArchiveOldRooms() error {
	// Implementation for archiving old rooms
	// For now, we keep all rooms accessible as specified
	return nil
}

// GetUserRooms returns Matrix rooms that a user has access to
func GetUserRooms(db *gorm.DB, userID uint) ([]MatrixRoom, error) {
	var rooms []MatrixRoom

	err := db.Raw(`
		SELECT mr.* FROM matrix_rooms mr
		INNER JOIN matrix_room_members mrm ON mr.id = mrm.room_id
		WHERE mrm.user_id = ?
		ORDER BY mr.created_at DESC
	`, userID).Scan(&rooms).Error

	if err != nil {
		return nil, fmt.Errorf("failed to get user rooms: %w", err)
	}

	// Preload cycle and content information
	for i := range rooms {
		db.Preload("Cycle.WinnerContent").Find(&rooms[i], rooms[i].ID)
	}

	return rooms, nil
}

// CleanupMatrixResources cleans up Matrix resources when features are disabled
func CleanupMatrixResources() error {
	// Implementation for cleanup when Matrix is disabled
	// For now, we don't automatically remove rooms to preserve chat history
	slog.Info("Matrix cleanup requested - preserving existing rooms and data")
	return nil
}

// GetUserCurrentMatrixRooms returns the actual Matrix rooms and memberships for a user
// This is used before account switching to preserve room access
func GetUserCurrentMatrixRooms(db *gorm.DB, watcharrUserID uint) ([]MatrixRoom, error) {
	var rooms []MatrixRoom

	// Get rooms where this user is a member
	err := db.Raw(`
		SELECT mr.* FROM matrix_rooms mr
		INNER JOIN matrix_room_members mrm ON mr.id = mrm.room_id
		WHERE mrm.user_id = ?
		ORDER BY mr.created_at DESC
	`, watcharrUserID).Scan(&rooms).Error

	if err != nil {
		return nil, fmt.Errorf("failed to get user's current Matrix rooms: %w", err)
	}

	return rooms, nil
}

// InviteUserToExistingRooms invites a Matrix user to a list of rooms
func InviteUserToExistingRooms(db *gorm.DB, matrixUserID string, watcharrUserID uint, rooms []MatrixRoom) error {
	if matrixClient == nil {
		return errors.New("matrix client not initialized")
	}

	if len(rooms) == 0 {
		slog.Info("No rooms to invite user to", "watcharr_user_id", watcharrUserID)
		return nil
	}

	successCount := 0
	errorCount := 0

	for _, room := range rooms {
		roomID := id.RoomID(room.RoomID)

		// Invite user to room
		_, err := matrixClient.InviteUser(context.Background(), roomID, &mautrix.ReqInviteUser{
			UserID: id.UserID(matrixUserID),
		})

		if err != nil {
			slog.Warn("Failed to invite custom Matrix user to existing room",
				"matrix_user_id", matrixUserID,
				"room_id", roomID,
				"room_alias", room.RoomAlias,
				"error", err)
			errorCount++
			continue
		}

		successCount++
		slog.Debug("Invited custom Matrix user to existing room",
			"matrix_user_id", matrixUserID,
			"room_id", roomID,
			"room_alias", room.RoomAlias)
	}

	slog.Info("Custom Matrix user invitation to existing rooms complete",
		"matrix_user_id", matrixUserID,
		"watcharr_user_id", watcharrUserID,
		"invited", successCount,
		"errors", errorCount,
		"total_rooms", len(rooms))

	return nil
}

// RemoveUserFromMatrixRooms removes a Matrix user from all their rooms
func RemoveUserFromMatrixRooms(db *gorm.DB, matrixUserID string, watcharrUserID uint) error {
	if matrixClient == nil {
		return errors.New("matrix client not initialized")
	}

	// Get user's current rooms
	rooms, err := GetUserCurrentMatrixRooms(db, watcharrUserID)
	if err != nil {
		return fmt.Errorf("failed to get user's rooms for cleanup: %w", err)
	}

	if len(rooms) == 0 {
		slog.Info("No rooms to remove user from", "matrix_user_id", matrixUserID)
		return nil
	}

	successCount := 0
	errorCount := 0

	for _, room := range rooms {
		roomID := id.RoomID(room.RoomID)

		// Kick/ban the user from the room (remove them)
		_, err := matrixClient.KickUser(context.Background(), roomID, &mautrix.ReqKickUser{
			UserID: id.UserID(matrixUserID),
			Reason: "Account being unlinked from Watcharr",
		})

		if err != nil {
			slog.Warn("Failed to remove Matrix user from room",
				"matrix_user_id", matrixUserID,
				"room_id", roomID,
				"room_alias", room.RoomAlias,
				"error", err)
			errorCount++
			continue
		}

		successCount++
		slog.Debug("Removed Matrix user from room",
			"matrix_user_id", matrixUserID,
			"room_id", roomID,
			"room_alias", room.RoomAlias)
	}

	slog.Info("Matrix user removal from rooms complete",
		"matrix_user_id", matrixUserID,
		"watcharr_user_id", watcharrUserID,
		"removed_from", successCount,
		"errors", errorCount,
		"total_rooms", len(rooms))

	return nil
}

// Retroactive room creation functions

// GetActiveWatchingCyclesWithoutRooms returns cycles in watching phase that don't have Matrix rooms
func GetActiveWatchingCyclesWithoutRooms(db *gorm.DB) ([]MovieClubCycle, error) {
	var cycles []MovieClubCycle
	now := time.Now()

	// Find cycles that are:
	// 1. In watching phase (phase = 'watching' AND phase_start_date <= now < phase_end_date)
	// 2. Have a winner content (winner_content_id IS NOT NULL)
	// 3. Don't already have a Matrix room
	err := db.Raw(`
		SELECT mcc.* FROM movie_club_cycles mcc
		WHERE mcc.phase = ?
		AND mcc.phase_start_date <= ?
		AND mcc.phase_end_date > ?
		AND mcc.winner_content_id IS NOT NULL
		AND mcc.id NOT IN (
			SELECT DISTINCT mr.cycle_id 
			FROM matrix_rooms mr 
			WHERE mr.cycle_id = mcc.id
		)
		ORDER BY mcc.phase_start_date ASC
	`, PHASE_WATCHING, now, now).Scan(&cycles).Error

	if err != nil {
		return nil, fmt.Errorf("failed to get active watching cycles without rooms: %w", err)
	}

	// Preload the winner content for each cycle
	for i := range cycles {
		if err := db.Preload("WinnerContent").Find(&cycles[i], cycles[i].ID).Error; err != nil {
			slog.Warn("Failed to preload winner content for cycle", 
				"cycle_id", cycles[i].ID, 
				"error", err)
		}
	}

	return cycles, nil
}

// CreateRoomsForExistingCycles creates Matrix rooms for active watching cycles that don't have them
func CreateRoomsForExistingCycles(db *gorm.DB) (*RetroactiveRoomCreationResult, error) {
	if !Config.MOVIE_CLUB.Matrix.Enabled {
		return nil, errors.New("matrix integration is not enabled")
	}

	if matrixClient == nil {
		return nil, errors.New("matrix client not initialized")
	}

	// Get cycles that need rooms
	cycles, err := GetActiveWatchingCyclesWithoutRooms(db)
	if err != nil {
		return nil, fmt.Errorf("failed to get cycles needing rooms: %w", err)
	}

	result := &RetroactiveRoomCreationResult{
		TotalCycles:    len(cycles),
		CreatedRooms:   0,
		FailedRooms:    0,
		CreatedRoomIDs: make([]string, 0),
		Errors:         make([]string, 0),
	}

	if len(cycles) == 0 {
		slog.Info("No active watching cycles found that need Matrix rooms")
		return result, nil
	}

	slog.Info("Creating Matrix rooms for existing watching cycles", 
		"cycle_count", len(cycles))

	// Create spaces and rooms for each cycle using the new space-based architecture
	for _, cycle := range cycles {
		var movieTitle string
		if cycle.WinnerContent != nil {
			movieTitle = cycle.WinnerContent.Title
		} else {
			movieTitle = fmt.Sprintf("Cycle %d", cycle.ID)
		}
		
		slog.Info("Creating Matrix space and rooms for existing cycle", 
			"cycle_id", cycle.ID,
			"cycle_name", cycle.Name,
			"movie_title", movieTitle)

		// Create cycle space
		cycleSpace, err := CreateCycleSpace(db, &cycle)
		if err != nil {
			errorMsg := fmt.Sprintf("Failed to create space for cycle %d (%s): %v", 
				cycle.ID, cycle.Name, err)
			slog.Error("Retroactive space creation failed", 
				"cycle_id", cycle.ID,
				"cycle_name", cycle.Name,
				"error", err)
			
			result.FailedRooms++
			result.Errors = append(result.Errors, errorMsg)
			continue
		}

		// Ensure Movie Club space exists and add cycle space to hierarchy
		movieClubSpace, err := EnsureMovieClubSpace(db)
		if err != nil {
			slog.Error("Failed to ensure Movie Club space", "error", err, "cycle_id", cycle.ID)
		} else {
			if err := SetupSpaceHierarchy(db, movieClubSpace, cycleSpace); err != nil {
				slog.Error("Failed to setup space hierarchy for cycle", "error", err, "cycle_id", cycle.ID, "space_id", cycleSpace.SpaceID)
			}
		}

		// Create General and Spoilers rooms in the cycle space
		if err := CreateCycleRooms(db, cycleSpace, &cycle); err != nil {
			errorMsg := fmt.Sprintf("Failed to create rooms for cycle %d (%s): %v", 
				cycle.ID, cycle.Name, err)
			slog.Error("Failed to create cycle rooms", "error", err, "cycle_id", cycle.ID, "space_id", cycleSpace.SpaceID)
			
			result.FailedRooms++
			result.Errors = append(result.Errors, errorMsg)
			continue
		}

		// Count both General and Spoilers rooms as created
		result.CreatedRooms += 2 // General + Spoilers
		
		// Get the created rooms to add their IDs to result
		var createdRooms []MatrixRoom
		if err := db.Where("space_id = ?", cycleSpace.SpaceID).Find(&createdRooms).Error; err == nil {
			for _, room := range createdRooms {
				result.CreatedRoomIDs = append(result.CreatedRoomIDs, room.RoomID)
			}
		}
		
		slog.Info("Successfully created Matrix space and rooms for existing cycle",
			"cycle_id", cycle.ID,
			"cycle_name", cycle.Name,
			"space_id", cycleSpace.SpaceID,
			"movie_title", movieTitle)
	}

	slog.Info("Retroactive room creation completed",
		"total_cycles", result.TotalCycles,
		"created_rooms", result.CreatedRooms,
		"failed_rooms", result.FailedRooms)

	return result, nil
}

// RetroactiveRoomCreationResult represents the result of creating rooms for existing cycles
type RetroactiveRoomCreationResult struct {
	TotalCycles    int      `json:"totalCycles"`
	CreatedRooms   int      `json:"createdRooms"`
	FailedRooms    int      `json:"failedRooms"`
	CreatedRoomIDs []string `json:"createdRoomIds"`
	Errors         []string `json:"errors"`
}

// Utility functions

// generateRoomAlias creates a Matrix room alias for a cycle
func generateRoomAlias(cycle *MovieClubCycle) string {
	// Format: movieclub-YYYY-MM-DD-normalized-title
	dateStr := cycle.VotingEndDate.Format("2006-01-02")
	
	var title string
	if cycle.WinnerContent != nil {
		title = cycle.WinnerContent.Title
	} else {
		// Fallback if winner content is not loaded
		title = fmt.Sprintf("cycle-%d", cycle.ID)
	}
	
	normalizedTitle := normalizeTitle(title)
	return fmt.Sprintf("movieclub-%s-%s", dateStr, normalizedTitle)
}

// normalizeTitle normalizes a movie title for use in Matrix room alias
func normalizeTitle(title string) string {
	// Convert to lowercase and replace non-alphanumeric characters with hyphens
	normalized := strings.ToLower(title)
	
	// Replace multiple spaces and special characters with single hyphen
	var result strings.Builder
	lastWasHyphen := false
	
	for _, r := range normalized {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			result.WriteRune(r)
			lastWasHyphen = false
		} else if !lastWasHyphen {
			result.WriteRune('-')
			lastWasHyphen = true
		}
	}
	
	// Remove trailing hyphen if present
	finalResult := strings.TrimSuffix(result.String(), "-")
	
	// Limit length to 50 characters to avoid Matrix alias length limits
	if len(finalResult) > 50 {
		finalResult = finalResult[:50]
		// Remove trailing hyphen that might have been created by truncation
		finalResult = strings.TrimSuffix(finalResult, "-")
	}
	
	return finalResult
}

// Enhanced Matrix Rooms Management for Spaces and Room Types

// EnsureNewsRoom creates or gets the global News room for all users
func EnsureNewsRoom(db *gorm.DB) (*MatrixRoom, error) {
	if matrixClient == nil {
		return nil, errors.New("matrix client not initialized")
	}

	// Check if News room already exists
	var existingRoom MatrixRoom
	if err := db.Where("room_type = ?", MatrixRoomTypeNews).First(&existingRoom).Error; err == nil {
		return &existingRoom, nil
	}

	// Ensure Movie Club space exists
	movieClubSpace, err := EnsureMovieClubSpace(db)
	if err != nil {
		return nil, fmt.Errorf("failed to ensure Movie Club space: %w", err)
	}

	// Create News room
	roomName := "News"
	createReq := &mautrix.ReqCreateRoom{
		Name:          roomName,
		Topic:         "Movie Club news and announcements",
		Preset:        "private_chat",
		Visibility:    "private",
		IsDirect:      false,
		RoomAliasName: "movieclub-news",
	}

	resp, err := matrixClient.CreateRoom(context.Background(), createReq)
	if err != nil {
		return nil, fmt.Errorf("failed to create News room: %w", err)
	}

	// Store room in database
	newsRoom := &MatrixRoom{
		RoomID:    resp.RoomID.String(),
		RoomAlias: fmt.Sprintf("#movieclub-news:%s", Config.MOVIE_CLUB.Matrix.ServerName),
		RoomName:  roomName,
		RoomType:  MatrixRoomTypeNews,
		SpaceID:   &movieClubSpace.SpaceID,
		CycleID:   nil, // News room is not associated with any cycle
	}

	if err := db.Create(newsRoom).Error; err != nil {
		return nil, fmt.Errorf("failed to store News room: %w", err)
	}

	slog.Info("Created News room",
		"room_id", resp.RoomID,
		"alias", newsRoom.RoomAlias)

	// Add room to Movie Club space
	if err := AddRoomToSpace(db, newsRoom, movieClubSpace); err != nil {
		slog.Warn("Failed to add News room to Movie Club space", "error", err)
	}

	// Invite all existing Matrix users to News room
	if err := InviteAllUsersToNewsRoom(db, newsRoom); err != nil {
		slog.Warn("Failed to invite all users to News room", "error", err)
	}

	return newsRoom, nil
}

// InviteAllUsersToNewsRoom invites all Matrix users to the News room
func InviteAllUsersToNewsRoom(db *gorm.DB, newsRoom *MatrixRoom) error {
	if matrixClient == nil {
		return errors.New("matrix client not initialized")
	}

	// Get all MatrixUserV2 records (both AS and personal accounts)
	var matrixUsers []MatrixUserV2
	if err := db.Preload("User").Find(&matrixUsers).Error; err != nil {
		return fmt.Errorf("failed to get Matrix users: %w", err)
	}

	roomID := id.RoomID(newsRoom.RoomID)
	successCount := 0
	errorCount := 0

	for _, matrixUser := range matrixUsers {
		// Skip invitation for placeholder accounts
		skipInvitation := false
		if matrixUser.AccountType == AccountTypePersonal && matrixUser.IsAutoGenerated {
			// Auto-generated personal accounts are placeholder only (shared secret registration removed)
			skipInvitation = true
		}

		if skipInvitation {
			slog.Debug("Skipping News room invitation for placeholder Matrix user",
				"matrix_user_id", matrixUser.MatrixUserID,
				"watcharr_user_id", matrixUser.UserID)
			continue
		}

		// Invite user to News room
		_, err := matrixClient.InviteUser(context.Background(), roomID, &mautrix.ReqInviteUser{
			UserID: id.UserID(matrixUser.MatrixUserID),
		})

		if err != nil {
			slog.Warn("Failed to invite user to News room",
				"matrix_user_id", matrixUser.MatrixUserID,
				"room_id", roomID,
				"error", err)
			errorCount++
			continue
		}

		// Record membership in database
		membership := &MatrixRoomMember{
			RoomID:   newsRoom.ID,
			UserID:   matrixUser.UserID,
			JoinedAt: time.Now(),
		}

		if err := db.Create(membership).Error; err != nil {
			slog.Warn("Failed to record News room membership", "error", err)
		}

		successCount++
		slog.Debug("Invited user to News room",
			"matrix_user_id", matrixUser.MatrixUserID,
			"room_id", roomID)
	}

	slog.Info("News room invitation complete",
		"room_id", roomID,
		"invited", successCount,
		"errors", errorCount)

	return nil
}

// InviteUserToNewsRoom invites a specific user to the News room (for new users)
func InviteUserToNewsRoom(db *gorm.DB, userID uint) error {
	if matrixClient == nil {
		return errors.New("matrix client not initialized")
	}

	// Get News room
	var newsRoom MatrixRoom
	if err := db.Where("room_type = ?", MatrixRoomTypeNews).First(&newsRoom).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			// News room doesn't exist yet, create it
			createdRoom, err := EnsureNewsRoom(db)
			if err != nil {
				return fmt.Errorf("failed to create News room: %w", err)
			}
			newsRoom = *createdRoom
		} else {
			return fmt.Errorf("failed to get News room: %w", err)
		}
	}

	// Get Matrix user
	var matrixUser MatrixUserV2
	if err := db.Where("user_id = ?", userID).First(&matrixUser).Error; err != nil {
		return fmt.Errorf("user does not have a Matrix account: %w", err)
	}

	// Skip invitation for placeholder accounts
	if matrixUser.AccountType == AccountTypePersonal && matrixUser.IsAutoGenerated {
		// Auto-generated personal accounts are placeholder only (shared secret registration removed)
		slog.Debug("Skipping News room invitation for placeholder Matrix user",
			"matrix_user_id", matrixUser.MatrixUserID,
			"watcharr_user_id", userID)
		return nil
	}

	// Check if user is already a member
	var existingMembership MatrixRoomMember
	if err := db.Where("room_id = ? AND user_id = ?", newsRoom.ID, userID).First(&existingMembership).Error; err == nil {
		slog.Debug("User already member of News room", "user_id", userID)
		return nil
	}

	// Invite user to News room
	roomID := id.RoomID(newsRoom.RoomID)
	_, err := matrixClient.InviteUser(context.Background(), roomID, &mautrix.ReqInviteUser{
		UserID: id.UserID(matrixUser.MatrixUserID),
	})

	if err != nil {
		return fmt.Errorf("failed to invite user to News room: %w", err)
	}

	// Record membership in database
	membership := &MatrixRoomMember{
		RoomID:   newsRoom.ID,
		UserID:   userID,
		JoinedAt: time.Now(),
	}

	if err := db.Create(membership).Error; err != nil {
		slog.Warn("Failed to record News room membership", "error", err)
	}

	slog.Info("Invited user to News room",
		"matrix_user_id", matrixUser.MatrixUserID,
		"user_id", userID,
		"room_id", roomID)

	return nil
}

// Space Hierarchy Management

// AddRoomToSpace adds a room to a space (replaces AddRoomToMovieClubSpace for new structure)
func AddRoomToSpace(db *gorm.DB, room *MatrixRoom, space *MatrixSpace) error {
	if matrixClient == nil {
		return errors.New("matrix client not initialized")
	}

	// Update database relationship
	room.SpaceID = &space.SpaceID
	if err := db.Save(room).Error; err != nil {
		return fmt.Errorf("failed to update room space relationship: %w", err)
	}

	spaceID := id.RoomID(space.SpaceID)
	childRoomID := id.RoomID(room.RoomID)

	// Add room as child of space
	stateKey := room.RoomID
	content := map[string]interface{}{
		"via": []string{Config.MOVIE_CLUB.Matrix.ServerName},
	}
	_, err := matrixClient.SendStateEvent(context.Background(), spaceID, event.StateSpaceChild, stateKey, content)

	if err != nil {
		return fmt.Errorf("failed to add room to space: %w", err)
	}

	// Add space as parent of room
	parentContent := map[string]interface{}{
		"via": []string{Config.MOVIE_CLUB.Matrix.ServerName},
	}
	_, err = matrixClient.SendStateEvent(context.Background(), childRoomID, event.StateSpaceParent, space.SpaceID, parentContent)

	if err != nil {
		slog.Warn("Failed to set space as parent of room", "error", err)
		// Don't return error as the main relationship is established
	}

	slog.Debug("Added room to space", "room_id", room.RoomID, "space_id", space.SpaceID)
	return nil
}

// SetupSpaceHierarchy establishes parent-child relationships between spaces
func SetupSpaceHierarchy(db *gorm.DB, parentSpace *MatrixSpace, childSpace *MatrixSpace) error {
	if matrixClient == nil {
		return errors.New("matrix client not initialized")
	}

	// Update database relationship
	childSpace.ParentSpaceID = &parentSpace.SpaceID
	if err := db.Save(childSpace).Error; err != nil {
		return fmt.Errorf("failed to update space hierarchy: %w", err)
	}

	parentSpaceID := id.RoomID(parentSpace.SpaceID)
	childSpaceID := id.RoomID(childSpace.SpaceID)

	// Add child space as child of parent space
	stateKey := childSpace.SpaceID
	content := map[string]interface{}{
		"via": []string{Config.MOVIE_CLUB.Matrix.ServerName},
	}
	_, err := matrixClient.SendStateEvent(context.Background(), parentSpaceID, event.StateSpaceChild, stateKey, content)

	if err != nil {
		return fmt.Errorf("failed to add child space to parent space: %w", err)
	}

	// Add parent space as parent of child space
	parentContent := map[string]interface{}{
		"via": []string{Config.MOVIE_CLUB.Matrix.ServerName},
	}
	_, err = matrixClient.SendStateEvent(context.Background(), childSpaceID, event.StateSpaceParent, parentSpace.SpaceID, parentContent)

	if err != nil {
		slog.Warn("Failed to set parent space as parent of child space", "error", err)
		// Don't return error as the main relationship is established
	}

	slog.Debug("Established space hierarchy", "parent_space_id", parentSpace.SpaceID, "child_space_id", childSpace.SpaceID)
	return nil
}

// Cycle Space Creation

// CreateCycleSpace creates a space for a movie club cycle
func CreateCycleSpace(db *gorm.DB, cycle *MovieClubCycle) (*MatrixSpace, error) {
	if matrixClient == nil {
		return nil, errors.New("matrix client not initialized")
	}

	// Check if space already exists for this cycle
	var existingSpace MatrixSpace
	if err := db.Where("cycle_id = ? AND space_type = ?", cycle.ID, MatrixSpaceTypeCycle).First(&existingSpace).Error; err == nil {
		slog.Debug("Space already exists for cycle", "cycle_id", cycle.ID, "space_id", existingSpace.SpaceID)
		return &existingSpace, nil
	}

	// Generate space name
	var movieTitle string
	if cycle.WinnerContent != nil {
		movieTitle = cycle.WinnerContent.Title
	} else {
		movieTitle = fmt.Sprintf("Cycle %d", cycle.ID)
	}
	
	spaceName := fmt.Sprintf("Cycle: %s (%s)",
		movieTitle,
		cycle.VotingEndDate.Format("2006-01-02"))

	// Create space
	createReq := &mautrix.ReqCreateRoom{
		Name:       spaceName,
		Topic:      fmt.Sprintf("Movie Club cycle space for %s", movieTitle),
		Preset:     "private_chat",
		Visibility: "private",
		CreationContent: map[string]interface{}{
			"type": "m.space",
		},
	}

	resp, err := matrixClient.CreateRoom(context.Background(), createReq)
	if err != nil {
		return nil, fmt.Errorf("failed to create cycle space: %w", err)
	}

	// Store space in database
	cycleSpace := &MatrixSpace{
		SpaceID:       resp.RoomID.String(),
		SpaceName:     spaceName,
		SpaceType:     MatrixSpaceTypeCycle,
		CycleID:       &cycle.ID,
		ParentSpaceID: nil, // Will be set when added to Movie Club space
	}

	if err := db.Create(cycleSpace).Error; err != nil {
		return nil, fmt.Errorf("failed to store cycle space: %w", err)
	}

	slog.Info("Created cycle space",
		"cycle_id", cycle.ID,
		"space_id", resp.RoomID,
		"space_name", spaceName,
		"movie", movieTitle)

	return cycleSpace, nil
}

// CreateCycleRooms creates General and Spoilers rooms in a cycle space
func CreateCycleRooms(db *gorm.DB, cycleSpace *MatrixSpace, cycle *MovieClubCycle) error {
	// Create General room
	generalRoom, err := createRoomInSpace(db, cycleSpace, cycle, MatrixRoomTypeGeneral, "General", "General discussion")
	if err != nil {
		return fmt.Errorf("failed to create General room: %w", err)
	}

	// Create Spoilers room
	spoilersRoom, err := createRoomInSpace(db, cycleSpace, cycle, MatrixRoomTypeSpoilers, "Spoilers", "Spoilers discussion")
	if err != nil {
		return fmt.Errorf("failed to create Spoilers room: %w", err)
	}

	// Invite eligible users to both rooms
	return InviteUsersToSpaceRooms(db, cycle.ID, []*MatrixRoom{generalRoom, spoilersRoom})
}

// createRoomInSpace creates a specific room type within a cycle space
func createRoomInSpace(db *gorm.DB, space *MatrixSpace, cycle *MovieClubCycle, roomType MatrixRoomType, roomName, roomTopic string) (*MatrixRoom, error) {
	if matrixClient == nil {
		return nil, errors.New("matrix client not initialized")
	}

	// Generate room alias
	var movieTitle string
	if cycle.WinnerContent != nil {
		movieTitle = cycle.WinnerContent.Title
	} else {
		movieTitle = fmt.Sprintf("cycle-%d", cycle.ID)
	}

	normalizedTitle := normalizeTitle(movieTitle)
	roomAlias := fmt.Sprintf("movieclub-%s-%s-%s", 
		cycle.VotingEndDate.Format("2006-01-02"), 
		normalizedTitle, 
		string(roomType))

	// Create room
	createReq := &mautrix.ReqCreateRoom{
		RoomAliasName: roomAlias,
		Name:          roomName,
		Topic:         roomTopic,
		Preset:        "private_chat",
		Visibility:    "private",
		IsDirect:      false,
	}

	resp, err := matrixClient.CreateRoom(context.Background(), createReq)
	if err != nil {
		return nil, fmt.Errorf("failed to create %s room: %w", roomType, err)
	}

	// Store room in database
	matrixRoom := &MatrixRoom{
		RoomID:    resp.RoomID.String(),
		RoomAlias: fmt.Sprintf("#%s:%s", roomAlias, Config.MOVIE_CLUB.Matrix.ServerName),
		RoomName:  roomName,
		RoomType:  roomType,
		SpaceID:   &space.SpaceID,
		CycleID:   &cycle.ID,
	}

	if err := db.Create(matrixRoom).Error; err != nil {
		return nil, fmt.Errorf("failed to store %s room: %w", roomType, err)
	}

	slog.Info("Created room in cycle space",
		"cycle_id", cycle.ID,
		"room_type", roomType,
		"room_id", resp.RoomID,
		"alias", matrixRoom.RoomAlias,
		"space_id", space.SpaceID)

	// Add room to space
	if err := AddRoomToSpace(db, matrixRoom, space); err != nil {
		slog.Warn("Failed to add room to cycle space", "error", err, "room_id", resp.RoomID)
	}

	return matrixRoom, nil
}

// Enhanced Invitation Management

// InviteUsersToSpaceRooms invites eligible cycle participants to space rooms
func InviteUsersToSpaceRooms(db *gorm.DB, cycleID uint, rooms []*MatrixRoom) error {
	if matrixClient == nil {
		return errors.New("matrix client not initialized")
	}

	// Get eligible users (nominated or voted in cycle)
	eligibleUsers, err := GetEligibleUsersForCycle(db, cycleID)
	if err != nil {
		return fmt.Errorf("failed to get eligible users: %w", err)
	}

	successCount := 0
	errorCount := 0

	for _, user := range eligibleUsers {
		// Get Matrix user for this Watcharr user using hybrid system
		matrixUser, err := GetOrCreateMatrixUserV2(db, user.ID, user.Username)
		if err != nil {
			slog.Warn("Failed to get Matrix user for cycle room invitation",
				"watcharr_user_id", user.ID,
				"username", user.Username,
				"error", err)
			errorCount++
			continue
		}

		// Skip invitation for placeholder accounts
		skipInvitation := false
		if matrixUser.AccountType == AccountTypePersonal && matrixUser.IsAutoGenerated {
			// Auto-generated personal accounts are placeholder only (shared secret registration removed)
			skipInvitation = true
		}

		if skipInvitation {
			slog.Debug("Skipping cycle room invitation for placeholder Matrix user",
				"matrix_user_id", matrixUser.MatrixUserID,
				"watcharr_user_id", user.ID)
			continue
		}

		// Invite to all rooms in the cycle space
		userSuccessCount := 0
		for _, room := range rooms {
			roomID := id.RoomID(room.RoomID)

			// Check if user is already a member
			var existingMembership MatrixRoomMember
			if err := db.Where("room_id = ? AND user_id = ?", room.ID, user.ID).First(&existingMembership).Error; err == nil {
				slog.Debug("User already member of room", "user_id", user.ID, "room_id", room.RoomID, "room_type", room.RoomType)
				userSuccessCount++
				continue
			}

			// Invite user to room
			_, err = matrixClient.InviteUser(context.Background(), roomID, &mautrix.ReqInviteUser{
				UserID: id.UserID(matrixUser.MatrixUserID),
			})

			if err != nil {
				slog.Warn("Failed to invite user to cycle room",
					"matrix_user_id", matrixUser.MatrixUserID,
					"room_id", roomID,
					"room_type", room.RoomType,
					"error", err)
				continue
			}

			// Record membership in database
			membership := &MatrixRoomMember{
				RoomID:   room.ID,
				UserID:   user.ID,
				JoinedAt: time.Now(),
			}

			if err := db.Create(membership).Error; err != nil {
				slog.Warn("Failed to record cycle room membership", "error", err)
			}

			userSuccessCount++
			slog.Debug("Invited user to cycle room",
				"matrix_user_id", matrixUser.MatrixUserID,
				"room_id", roomID,
				"room_type", room.RoomType)
		}

		if userSuccessCount > 0 {
			successCount++
		} else {
			errorCount++
		}
	}

	slog.Info("Cycle room invitation complete",
		"cycle_id", cycleID,
		"invited_users", successCount,
		"errors", errorCount,
		"total_rooms", len(rooms))

	return nil
}

// MigrateExistingRoomsToSpaces migrates existing Matrix rooms to the new space-based structure
func MigrateExistingRoomsToSpaces(db *gorm.DB) (*MatrixRoomMigrationResult, error) {
	if !Config.MOVIE_CLUB.Matrix.Enabled {
		return nil, errors.New("matrix integration is not enabled")
	}

	if matrixClient == nil {
		return nil, errors.New("matrix client not initialized")
	}

	result := &MatrixRoomMigrationResult{
		TotalRooms:     0,
		MigratedRooms:  0,
		FailedRooms:    0,
		CreatedSpaces:  0,
		Errors:         make([]string, 0),
	}

	// Find all existing Matrix rooms that need migration (rooms without space or room_type)
	var existingRooms []MatrixRoom
	if err := db.Where("space_id IS NULL OR room_type IS NULL OR room_type = ''").
		Preload("Cycle").
		Preload("Cycle.WinnerContent").
		Find(&existingRooms).Error; err != nil {
		return nil, fmt.Errorf("failed to get existing rooms: %w", err)
	}

	result.TotalRooms = len(existingRooms)

	if len(existingRooms) == 0 {
		slog.Info("No Matrix rooms found that need migration")
		return result, nil
	}

	slog.Info("Starting migration of existing Matrix rooms to space structure", 
		"room_count", len(existingRooms))

	// Ensure Movie Club space exists
	movieClubSpace, err := EnsureMovieClubSpace(db)
	if err != nil {
		return nil, fmt.Errorf("failed to ensure Movie Club space: %w", err)
	}

	// Process each existing room
	for _, room := range existingRooms {
		if room.CycleID == nil {
			// This is likely a legacy room without cycle association, skip it
			slog.Warn("Skipping room without cycle association", "room_id", room.RoomID)
			continue
		}

		// Create cycle space for this room's cycle
		cycleSpace, err := CreateCycleSpace(db, room.Cycle)
		if err != nil {
			errorMsg := fmt.Sprintf("Failed to create cycle space for room %s: %v", room.RoomID, err)
			slog.Error(errorMsg)
			result.FailedRooms++
			result.Errors = append(result.Errors, errorMsg)
			continue
		}
		result.CreatedSpaces++

		// Add cycle space to Movie Club space hierarchy
		if err := SetupSpaceHierarchy(db, movieClubSpace, cycleSpace); err != nil {
			slog.Warn("Failed to setup space hierarchy for migrated cycle", 
				"error", err, "cycle_id", room.CycleID, "space_id", cycleSpace.SpaceID)
		}

		// Update the existing room to be a "General" room in the new space
		room.SpaceID = &cycleSpace.SpaceID
		room.RoomType = MatrixRoomTypeGeneral

		if err := db.Save(&room).Error; err != nil {
			errorMsg := fmt.Sprintf("Failed to update room %s: %v", room.RoomID, err)
			slog.Error(errorMsg)
			result.FailedRooms++
			result.Errors = append(result.Errors, errorMsg)
			continue
		}

		// Add the existing room to the cycle space
		if err := AddRoomToSpace(db, &room, cycleSpace); err != nil {
			slog.Warn("Failed to add migrated room to space", 
				"error", err, "room_id", room.RoomID, "space_id", cycleSpace.SpaceID)
		}

		// Create a Spoilers room for the cycle
		spoilersRoom, err := createRoomInSpace(db, cycleSpace, room.Cycle, 
			MatrixRoomTypeSpoilers, "Spoilers", "Spoiler discussions for this movie")
		if err != nil {
			slog.Warn("Failed to create Spoilers room during migration", 
				"error", err, "cycle_id", room.CycleID)
		} else {
			// Invite eligible users to the new Spoilers room
			if err := InviteUsersToSpaceRooms(db, *room.CycleID, []*MatrixRoom{spoilersRoom}); err != nil {
				slog.Warn("Failed to invite users to migrated Spoilers room", "error", err)
			}
		}

		result.MigratedRooms++
		slog.Info("Successfully migrated room to space structure",
			"room_id", room.RoomID,
			"cycle_id", room.CycleID,
			"space_id", cycleSpace.SpaceID)
	}

	slog.Info("Matrix room migration completed",
		"total_rooms", result.TotalRooms,
		"migrated_rooms", result.MigratedRooms,
		"failed_rooms", result.FailedRooms,
		"created_spaces", result.CreatedSpaces)

	return result, nil
}

// MatrixRoomMigrationResult represents the result of migrating existing rooms to spaces
type MatrixRoomMigrationResult struct {
	TotalRooms     int      `json:"totalRooms"`
	MigratedRooms  int      `json:"migratedRooms"`
	FailedRooms    int      `json:"failedRooms"`
	CreatedSpaces  int      `json:"createdSpaces"`
	Errors         []string `json:"errors"`
}